# team_fotmob_urls.py
import unicodedata

def _norm(s: str) -> str:
    if s is None:
        return ""
    s = unicodedata.normalize("NFKD", str(s)).encode("ascii", "ignore").decode("ascii")
    return " ".join(s.strip().lower().split())

# =====================================================
# PASTE FOTMOB URLS ONLY
# Leave "" if you don't have it yet
# =====================================================

FOTMOB_TEAM_URLS = {

    # --- ENGLAND / UK ---
    "Liverpool": "https://www.fotmob.com/teams/8650/squad/liverpool",
    "Sunderland": "https://www.fotmob.com/teams/8472/squad/sunderland",
    "Arsenal": "https://www.fotmob.com/teams/9825/squad/arsenal",
    "Bournemouth": "https://www.fotmob.com/teams/8678/squad/afc-bournemouth",
    "Brighton": "https://www.fotmob.com/teams/10204/squad/brighton-hove-albion",
    "Fulham": "https://www.fotmob.com/teams/9879/squad/fulham",
    "West Ham United": "https://www.fotmob.com/teams/8654/squad/west-ham-united",
    "Brentford": "https://www.fotmob.com/teams/9937/squad/brentford",
    "Crystal Palace": "https://www.fotmob.com/teams/9826/squad/crystal-palace",
    "Burnley": "https://www.fotmob.com/teams/8191/squad/burnley",
    "Tottenham Hotspur": "https://www.fotmob.com/teams/8586/squad/tottenham-hotspur",
    "Nottingham Forest": "https://www.fotmob.com/teams/10203/squad/nottingham-forest",
    "Everton": "https://www.fotmob.com/teams/8668/squad/everton",
    "Aston Villa": "https://www.fotmob.com/teams/10252/squad/aston-villa",
    "Manchester City": "https://www.fotmob.com/teams/8456/squad/manchester-city",
    "Manchester United": "https://www.fotmob.com/teams/10260/squad/manchester-united",
    "Newcastle United": "https://www.fotmob.com/teams/10261/squad/newcastle-united",
    "Chelsea": "https://www.fotmob.com/teams/8455/squad/chelsea",
    "Leeds United": "https://www.fotmob.com/teams/8463/squad/leeds-united",
    "Wolverhampton Wanderers": "https://www.fotmob.com/teams/8602/squad/wolverhampton-wanderers",
    "Derby County": "https://www.fotmob.com/teams/10170/squad/derby-county",
    "Coventry City": "https://www.fotmob.com/teams/8669/squad/coventry-city",
    "Norwich City": "https://www.fotmob.com/teams/9850/squad/norwich-city",
    "Swansea City": "https://www.fotmob.com/teams/10003/squad/swansea-city",
    "Middlesbrough": "https://www.fotmob.com/teams/8549/squad/middlesbrough",
    "Preston North End": "https://www.fotmob.com/teams/8411/squad/preston-north-end",
    "Millwall": "https://www.fotmob.com/teams/10004/squad/millwall",
    "Stoke City": "https://www.fotmob.com/teams/10194/squad/stoke-city",
    "Hull City": "",
    "Charlton Athletic": "https://www.fotmob.com/teams/8451/squad/charlton-athletic",
    "Wrexham": "https://www.fotmob.com/teams/9841/squad/wrexham",
    "Oxford United": "https://www.fotmob.com/teams/8653/squad/oxford-united",
    "Ipswich Town": "https://www.fotmob.com/teams/9902/squad/ipswich-town",
    "Birmingham City": "https://www.fotmob.com/teams/8658/squad/birmingham-city",
    "Bristol City": "https://www.fotmob.com/teams/8427/squad/bristol-city",
    "Sheffield United": "https://www.fotmob.com/teams/8657/squad/sheffield-united",
    "Sheffield Wednesday": "https://www.fotmob.com/teams/10163/squad/sheffield-wednesday",
    "West Bromwich Albion": "https://www.fotmob.com/teams/8659/squad/west-bromwich-albion",
    "Queens Park Rangers": "https://www.fotmob.com/teams/10172/squad/queens-park-rangers",
    "Leicester City": "https://www.fotmob.com/teams/8197/squad/leicester-city",
    "Blackburn Rovers": "https://www.fotmob.com/teams/8655/squad/blackburn-rovers",
    "Portsmouth": "https://www.fotmob.com/teams/8462/squad/portsmouth",
    "Southampton": "https://www.fotmob.com/teams/8466/squad/southampton",
    "Watford": "https://www.fotmob.com/teams/9817/squad/watford",
    "Lincoln City": "https://www.fotmob.com/teams/8430/squad/lincoln-city",
    "Plymouth Argyle": "https://www.fotmob.com/teams/8401/squad/plymouth-argyle",
    "Bradford City": "https://www.fotmob.com/teams/8484/squad/bradford-city",
    "Stockport County": "https://www.fotmob.com/teams/10007/squad/stockport-county",
    "Exeter City": "https://www.fotmob.com/teams/9833/squad/exeter-city",
    "Doncaster Rovers": "https://www.fotmob.com/teams/9903/squad/doncaster-rovers",
    "Rotherham United": "https://www.fotmob.com/teams/8119/squad/rotherham-united",
    "AFC Wimbledon": "https://www.fotmob.com/teams/158319/squad/afc-wimbledon",
    "Wigan Athletic": "https://www.fotmob.com/teams/8528/squad/wigan-athletic",
    "Blackpool": "https://www.fotmob.com/teams/8483/squad/blackpool",
    "Reading": "https://www.fotmob.com/teams/9798/squad/reading",
    "Peterborough United": "https://www.fotmob.com/teams/8677/squad/peterborough-united",
    "Mansfield Town": "https://www.fotmob.com/teams/9818/squad/mansfield-town",
    "Burton Albion": "https://www.fotmob.com/teams/9792/squad/burton-albion",
    "Wycombe Wanderers": "https://www.fotmob.com/teams/8676/squad/wycombe-wanderers",
    "Bolton Wanderers": "https://www.fotmob.com/teams/8559/squad/bolton-wanderers",
    "Luton Town": "https://www.fotmob.com/teams/8346/squad/luton-town",
    "Stevenage": "https://www.fotmob.com/teams/10253/squad/stevenage",
    "Cardiff City": "https://www.fotmob.com/teams/8344/squad/cardiff-city",
    "Huddersfield Town": "https://www.fotmob.com/teams/9796/squad/huddersfield-town",
    "Barnsley": "https://www.fotmob.com/teams/8283/squad/barnsley",
    "Northampton Town": "https://www.fotmob.com/teams/8651/squad/northampton-town",
    "Leyton Orient": "https://www.fotmob.com/teams/8351/squad/leyton-orient",
    "Port Vale": "https://www.fotmob.com/teams/9799/squad/port-vale",
    "Crawley Town": "https://www.fotmob.com/teams/8647/squad/crawley-town",
    "Chesterfield": "https://www.fotmob.com/teams/9786/squad/chesterfield",
    "Cheltenham Town": "https://www.fotmob.com/teams/8680/squad/cheltenham-town",
    "Colchester United": "https://www.fotmob.com/teams/8416/squad/colchester-united",
    "Grimsby Town": "https://www.fotmob.com/teams/10005/squad/grimsby-town",
    "Swindon Town": "https://www.fotmob.com/teams/9795/squad/swindon-town",
    "Oldham Athletic": "https://www.fotmob.com/teams/9785/squad/oldham-athletic",
    "Tranmere Rovers": "https://www.fotmob.com/teams/8313/squad/tranmere-rovers",
    "Cambridge United": "https://www.fotmob.com/teams/9834/squad/cambridge-united",
    "Notts County": "https://www.fotmob.com/teams/9819/squad/notts-county",
    "Walsall": "https://www.fotmob.com/teams/10006/squad/walsall",
    "Salford City": "https://www.fotmob.com/teams/282326/squad/salford-city",
    "Fleetwood Town": "https://www.fotmob.com/teams/45723/squad/fleetwood-town",
    "Barnet": "https://www.fotmob.com/teams/8175/squad/barnet",
    "Newport County": "https://www.fotmob.com/teams/10262/squad/newport-county",
    "Bromley": "https://www.fotmob.com/teams/45729/squad/bromley",
    "Shrewsbury Town": "https://www.fotmob.com/teams/9896/squad/shrewsbury-town",
    "Barrow": "https://www.fotmob.com/teams/6350/squad/barrow",
    "Milton Keynes Dons": "https://www.fotmob.com/teams/8645/squad/milton-keynes-dons",
    "Crewe Alexandra": "https://www.fotmob.com/teams/9784/squad/crewe-alexandra",
    "Gillingham": "https://www.fotmob.com/teams/10173/squad/gillingham",
    "Harrogate Town": "https://www.fotmob.com/teams/7946/squad/harrogate-town",
    "Accrington Stanley": "https://www.fotmob.com/teams/8671/squad/accrington-stanley",
    "Bristol Rovers": "https://www.fotmob.com/teams/10104/squad/bristol-rovers",
    "Halifax Town": "https://www.fotmob.com/teams/10195/squad/fc-halifax-town",
    "Eastleigh": "https://www.fotmob.com/teams/161803/squad/eastleigh",
    "Yeovil Town": "https://www.fotmob.com/teams/10198/squad/yeovil-town",
    "Woking": "https://www.fotmob.com/teams/8345/squad/woking",
    "Boston United": "https://www.fotmob.com/teams/8646/squad/boston-united",
    "Solihull Moors": "https://www.fotmob.com/teams/161801/squad/solihull-moors",
    "Forest Green Rovers": "https://www.fotmob.com/teams/9828/squad/forest-green-rovers",
    "Truro City": "https://www.fotmob.com/teams/177067/squad/truro-city",
    "York City": "https://www.fotmob.com/teams/9916/squad/york-city",
    "Hartlepool United": "https://www.fotmob.com/teams/8488/squad/hartlepool-united",
    "Wealdstone": "https://www.fotmob.com/teams/161812/squad/wealdstone",
    "Tamworth": "https://www.fotmob.com/teams/10254/squad/tamworth",
    "Braintree Town": "https://www.fotmob.com/teams/5763/squad/braintree-town",
    "Altrincham": "https://www.fotmob.com/teams/9915/squad/altrincham",
    "Gateshead": "https://www.fotmob.com/teams/6189/squad/gateshead-fc",
    "Boreham Wood": "https://www.fotmob.com/teams/2488/squad/boreham-wood",
    "Carlisle United": "https://www.fotmob.com/teams/10196/squad/carlisle-united",
    "Sutton United": "https://www.fotmob.com/teams/158316/squad/sutton-united",
    "Brackley Town": "https://www.fotmob.com/teams/158321/squad/brackley-town",
    "Southend United": "https://www.fotmob.com/teams/8652/squad/southend-united",
    "Aldershot Town": "https://www.fotmob.com/teams/8465/squad/aldershot-town",
    "Rochdale": "https://www.fotmob.com/teams/8493/squad/rochdale",
    "Morecambe": "https://www.fotmob.com/teams/8489/squad/morecambe",
    "Scunthorpe United": "https://www.fotmob.com/teams/8412/squad/scunthorpe-united",

    # --- ALBANIA ---
    "Flamurtari Vlorë": "https://www.fotmob.com/teams/10030/overview/flamurtari",
    "AF Elbasani": "https://www.fotmob.com/teams/10038/overview/elbasani",
    "Teuta Durrës": "https://www.fotmob.com/teams/10037/overview/teuta-durres",
    "Egnatia Rrogozhinë": "https://www.fotmob.com/teams/10039/overview/egnatia",
    "Vllaznia Shkodër": "https://www.fotmob.com/teams/10034/overview/vllaznia",
    "Dinamo City": "https://www.fotmob.com/teams/10027/overview/fc-dinamo-city",
    "Bylis Ballsh": "https://www.fotmob.com/teams/10026/overview/bylis",
    "Tirana": "https://www.fotmob.com/teams/10029/overview/kf-tirana",
    "Vora": "https://www.fotmob.com/teams/585403/overview/vora",
    "Partizani Tirana": "https://www.fotmob.com/teams/10028/overview/partizani",

    # --- ARGENTINA ---
    "Boca Juniors": "https://www.fotmob.com/teams/10077/squad/boca-juniors",
    "River Plate": "https://www.fotmob.com/teams/10076/squad/river-plate",
    "Racing Club": "https://www.fotmob.com/teams/10080/squad/racing-club",
    "Independiente": "https://www.fotmob.com/teams/10078/squad/independiente",
    "San Lorenzo": "https://www.fotmob.com/teams/10083/squad/san-lorenzo",
    "Lanús": "https://www.fotmob.com/teams/10082/squad/lanus",
    "Rosario Central": "https://www.fotmob.com/teams/10084/squad/rosario-central",
    "Huracán": "https://www.fotmob.com/teams/10081/squad/huracan",
    "Estudiantes": "https://www.fotmob.com/teams/10094/squad/estudiantes",
    "Vélez Sarsfield": "https://www.fotmob.com/teams/10079/squad/velez-sarsfield",
    "Banfield": "https://www.fotmob.com/teams/10087/squad/banfield",
    "Defensa y Justicia": "https://www.fotmob.com/teams/161730/squad/defensa-y-justicia",

    # --- ARMENIA ---
    "Pyunik": "https://www.fotmob.com/teams/6345/overview/pyunik",
    "Ararat": "https://www.fotmob.com/teams/866109/overview/ararat-armenia",
    "Urartu": "https://www.fotmob.com/teams/7979/overview/urartu-fc",
    "Noah": "https://www.fotmob.com/teams/866111/squad/fc-noah",
    "BKMA": "https://www.fotmob.com/teams/1078402/overview/bkma",

    # --- AUSTRALIA ---
    "Sydney": "https://www.fotmob.com/teams/10164/squad/sydney-fc",
    "Melbourne City": "https://www.fotmob.com/teams/203576/squad/melbourne-city-fc",
    "Melbourne Victory": "https://www.fotmob.com/teams/6230/overview/melbourne-victory",
    "Western Sydney Wanderers": "https://www.fotmob.com/teams/323834/squad/western-sydney-wanderers-fc",
    "Brisbane Roar": "https://www.fotmob.com/teams/8118/squad/brisbane-roar-fc",
    "Adelaide United": "https://www.fotmob.com/teams/8008/squad/adelaide-united",
    "Central Coast Mariners": "https://www.fotmob.com/teams/8164/squad/central-coast-mariners",
    "Perth Glory": "https://www.fotmob.com/teams/7961/squad/perth-glory",
    "Newcastle Jets": "https://www.fotmob.com/teams/6454/squad/newcastle-jets",
    "Wellington Phoenix": "https://www.fotmob.com/teams/78785/squad/wellington-phoenix",
    "Macarthur": "https://www.fotmob.com/teams/1209973/squad/macarthur-fc",
    "Auckland FC": "https://www.fotmob.com/teams/1642068/squad/auckland-fc",

    # --- AUSTRIA ---
    "Grazer AK": "https://www.fotmob.com/teams/10012/squad/grazer-ak",
    "LASK": "https://www.fotmob.com/teams/9977/squad/lask",
    "Austria Wien": "https://www.fotmob.com/teams/10011/squad/austria-wien",
    "Rheindorf Altach": "https://www.fotmob.com/teams/10008/squad/altach",
    "Blau-Weiß Linz": "https://www.fotmob.com/teams/2433/squad/bw-linz",
    "Ried": "https://www.fotmob.com/teams/10017/squad/ried",
    "WSG Swarovski Tirol": "https://www.fotmob.com/teams/1583/squad/wsg-tirol",
    "Hartberg": "https://www.fotmob.com/teams/10056/squad/hartberg",
    "Sturm Graz": "https://www.fotmob.com/teams/10014/squad/sturm-graz",
    "Salzburg": "https://www.fotmob.com/teams/10013/squad/salzburg",
    "Rapid Wien": "https://www.fotmob.com/teams/10015/squad/rapid-wien",
    "Wolfsberger AC": "https://www.fotmob.com/teams/1954/squad/wolfsberger-ac",
    "Austria Lustenau": "https://www.fotmob.com/teams/9982/squad/austria-lustenau",
    "St. Pölten": "https://www.fotmob.com/teams/1907/squad/skn-st-polten",
    "Bregenz": "https://www.fotmob.com/teams/80619/squad/sw-bregenz",
    "Rapid Wien II": "https://www.fotmob.com/teams/1952/squad/rapid-wien-ii",
    "Austria Salzburg": "https://www.fotmob.com/teams/206091/squad/austria-salzburg",
    "Floridsdorfer AC": "https://www.fotmob.com/teams/8274/squad/floridsdorfer-ac",
    "Kapfenberger SV": "https://www.fotmob.com/teams/9979/squad/kapfenberger-sv",
    "Austria Wien II": "https://www.fotmob.com/teams/10248/squad/austria-wien-ii",
    "Liefering": "https://www.fotmob.com/teams/1915/squad/fc-liefering",
    "Austria Klagenfurt": "https://www.fotmob.com/teams/10009/squad/sk-austria-klagenfurt",
    "Amstetten": "https://www.fotmob.com/teams/8326/squad/amstetten",
    "WSPG Wels": "https://www.fotmob.com/teams/946908/squad/spg-hogo-wels",
    "Admira": "https://www.fotmob.com/teams/10053/squad/admira-wacker",
    "Sturm Graz II": "https://www.fotmob.com/teams/1921/squad/sturm-graz-ii",
    "First Vienna": "https://www.fotmob.com/teams/2030/squad/first-vienna-fc",
    "Stripfing": "https://www.fotmob.com/teams/611179/overview/sv-stripfing",

    # --- AZERBAIJAN ---
    "Sabah": "https://www.fotmob.com/teams/951893/overview/sabah-fk",
    "Neftchi": "https://www.fotmob.com/teams/4617/overview/fk-neftchi",
    "Zira": "https://www.fotmob.com/teams/577619/overview/zira",
    "Shamakhi FK": "https://www.fotmob.com/teams/2103/overview/shamakhi-fk",
    "Karvan": "https://www.fotmob.com/teams/8045/overview/karvan-fk",
    "İmişli": "https://www.fotmob.com/teams/1786024/overview/imisli-fk",
    "Turan-T": "https://www.fotmob.com/teams/4674/overview/turan-tovuz",
    "Qabala": "https://www.fotmob.com/teams/8076/overview/fk-qabala",
    "Araz": "https://www.fotmob.com/teams/485832/overview/araz-pfk",
    "Kapaz": "https://www.fotmob.com/teams/4150/overview/fc-kapaz",
    "Sumqayıt": "https://www.fotmob.com/teams/213987/overview/sumqayit",
    "Qarabag": "https://www.fotmob.com/teams/7981/overview/qarabag-fk",

    # --- BELGIUM ---
    "Club Brugge": "https://www.fotmob.com/teams/8342/squad/club-brugge",
    "Sint-Truiden": "https://www.fotmob.com/teams/9997/squad/sttruiden",
    "Genk": "https://www.fotmob.com/teams/9987/squad/genk",
    "La Louvière": "https://www.fotmob.com/teams/1218969/squad/raal-la-louviere",
    "Zulte-Waregem": "https://www.fotmob.com/teams/10000/squad/zulte-waregem",
    "Antwerp": "https://www.fotmob.com/teams/9988/squad/royal-antwerp",
    "Westerlo": "https://www.fotmob.com/teams/10001/squad/westerlo",
    "OH Leuven": "https://www.fotmob.com/teams/1773/squad/oh-leuven",
    "Anderlecht": "https://www.fotmob.com/teams/8635/squad/anderlecht",
    "Gent": "https://www.fotmob.com/teams/9991/squad/gent",
    "Dender": "https://www.fotmob.com/teams/7947/squad/fcv-dender-eh",
    "Cercle Brugge": "https://www.fotmob.com/teams/9984/squad/cercle-brugge",
    "Mechelen": "https://www.fotmob.com/teams/8203/squad/kv-mechelen",
    "Charleroi": "https://www.fotmob.com/teams/9986/squad/sporting-charleroi",
    "Standard Liège": "https://www.fotmob.com/teams/9985/squad/standard-liege",
    "Union Saint-Gilloise": "https://www.fotmob.com/teams/7978/squad/union-stgilloise",
    "Patro Eisden": "https://www.fotmob.com/teams/274583/overview/patro-eisden",
    "Beerschot VA": "https://www.fotmob.com/teams/583877/overview/beerschot",
    "Francs Borains": "https://www.fotmob.com/teams/96953/overview/francs-borains",
    "Kortrijk": "https://www.fotmob.com/teams/8571/overview/kortrijk",
    "Lommel SK": "https://www.fotmob.com/teams/6702/overview/lommel",
    "Lokeren-Temse": "https://www.fotmob.com/teams/213307/overview/ksc-lokeren",
    "Lierse Kempenzonen": "https://www.fotmob.com/teams/465631/overview/k-lierse-sk",
    "Liège": "https://www.fotmob.com/teams/6363/overview/fc-liege",
    "Eupen": "https://www.fotmob.com/teams/6351/overview/eupen",
    "Club Brugge II": "https://www.fotmob.com/teams/1173026/overview/club-brugge-nxt",
    "RFC Seraing": "https://www.fotmob.com/teams/149408/overview/rfc-seraing",
    "SK Beveren": "https://www.fotmob.com/teams/8475/overview/sk-beveren",
    "Gent II": "https://www.fotmob.com/teams/1379188/overview/gent-u23",
    "Olympic Charleroi": "https://www.fotmob.com/teams/4137/overview/olympic-de-charleroi",
    "Genk II": "https://www.fotmob.com/teams/1378463/overview/genk-u23",
    "Anderlecht II": "https://www.fotmob.com/teams/1378461/overview/anderlecht-futures",
    "RWD Molenbeek": "https://www.fotmob.com/teams/9992/overview/rwdm-brussels",

    # --- BOLIVIA ---
    "Guabirá": "https://www.fotmob.com/teams/114830/squad/guabira",
    "Real Tomayapo": "https://www.fotmob.com/teams/1074622/squad/real-tomayapo",
    "Always Ready": "https://www.fotmob.com/teams/805913/squad/always-ready",
    "Real Oruro": "https://www.fotmob.com/teams/1504766/squad/cdt-real-oruro",
    "Universitario de Vinto": "https://www.fotmob.com/teams/879029/squad/universitario-de-vinto",
    "The Strongest": "https://www.fotmob.com/teams/2527/squad/strongest",
    "Wilstermann": "https://www.fotmob.com/teams/1892/squad/jorge-wilstermann",
    "Gualberto Villarroel SJ": "https://www.fotmob.com/teams/1504770/squad/gv-san-jose",
    "Aurora": "https://www.fotmob.com/teams/49720/squad/aurora",
    "Blooming": "https://www.fotmob.com/teams/49678/squad/blooming",
    "Independiente Petrolero": "https://www.fotmob.com/teams/958325/squad/independiente-petrolero",
    "San Antonio Bulo Bulo": "https://www.fotmob.com/teams/1297060/squad/san-antonio-bulo-bulo",
    "Nacional Potosí": "https://www.fotmob.com/teams/164353/squad/nacional-potosi",
    "Bolívar": "https://www.fotmob.com/teams/5983/squad/bolivar",
    "ABB": "https://www.fotmob.com/teams/1297346/squad/abb",
    "Oriente Petrolero": "https://www.fotmob.com/teams/1844/squad/oriente-petrolero",

    # --- BOSNIA ---
    "Željezničar": "https://www.fotmob.com/teams/10108/overview/zeljeznicar",
    "Široki Brijeg": "https://www.fotmob.com/teams/10112/overview/siroki-brijeg",
    "Sloga Doboj": "https://www.fotmob.com/teams/187928/overview/sloga-doboj",
    "Posušje": "https://www.fotmob.com/teams/10111/overview/posusje",
    "Sarajevo": "https://www.fotmob.com/teams/10105/overview/fk-sarajevo",
    "Borac Banja Luka": "https://www.fotmob.com/teams/10116/overview/borac-banja-luka",
    "Rudar Prijedor": "https://www.fotmob.com/teams/175797/overview/rudar-prijedor",
    "Radnik Bijeljina": "https://www.fotmob.com/teams/10124/overview/radnik-bijeljina",
    "Velež": "https://www.fotmob.com/teams/10122/overview/fk-velez-mostar",
    "Zrinjski": "https://www.fotmob.com/teams/10107/squad/zrinjski-mostar",

    # --- BRAZIL ---
    "Fluminense": "https://www.fotmob.com/teams/9863/squad/fluminense",
    "Santos": "https://www.fotmob.com/teams/8514/squad/santos-fc",
    "Mirassol": "https://www.fotmob.com/teams/163782/squad/mirassol",
    "Flamengo": "https://www.fotmob.com/teams/9770/squad/flamengo",
    "Atlético Mineiro": "https://www.fotmob.com/teams/10272/squad/atletico-mg",
    "Ceará": "https://www.fotmob.com/teams/172341/squad/ceara",
    "Vasco da Gama": "https://www.fotmob.com/teams/10276/squad/vasco-da-gama",
    "São Paulo": "https://www.fotmob.com/teams/10277/squad/sao-paulo",
    "Cruzeiro": "https://www.fotmob.com/teams/9781/squad/cruzeiro",
    "Red Bull Bragantino": "https://www.fotmob.com/teams/109705/squad/red-bull-bragantino",
    "Bahia": "https://www.fotmob.com/teams/7877/squad/bahia",
    "Grêmio": "https://www.fotmob.com/teams/9769/squad/gremio",
    "Vitória": "https://www.fotmob.com/teams/7733/squad/vitoria",
    "Botafogo": "https://www.fotmob.com/teams/8517/squad/botafogo-rj",
    "Juventude": "https://www.fotmob.com/teams/10274/overview/juventude",
    "Internacional": "https://www.fotmob.com/teams/8702/squad/internacional",
    "Sport Recife": "https://www.fotmob.com/teams/6305/squad/sport-recife",
    "Corinthians": "https://www.fotmob.com/teams/9808/squad/corinthians",
    "Fortaleza": "https://www.fotmob.com/teams/8287/squad/fortaleza",
    "Palmeiras": "https://www.fotmob.com/teams/10283/squad/palmeiras",
    "Ferroviária": "https://www.fotmob.com/teams/581832/squad/ferroviaria",
    "Chapecoense": "https://www.fotmob.com/teams/197693/squad/chapecoense-af",
    "Goiás": "https://www.fotmob.com/teams/9862/overview/goias",
    "América Mineiro": "https://www.fotmob.com/teams/1757/overview/america-mg",
    "Avaí": "https://www.fotmob.com/teams/104822/squad/avai-fc",
    "Remo": "https://www.fotmob.com/teams/1626/squad/remo",
    "Criciúma": "https://www.fotmob.com/teams/7729/squad/criciuma",
    "CRB": "https://www.fotmob.com/teams/104821/squad/crb",
    "Botafogo SP": "https://www.fotmob.com/teams/8355/squad/botafogo-sp",
    "Athletic Club": "https://www.fotmob.com/teams/1221604/overview/athletic-club",
    "Vila Nova": "https://www.fotmob.com/teams/109706/overview/vila-nova",
    "Operário PR": "https://www.fotmob.com/teams/197429/squad/operario-ferroviario",
    "Grêmio Novorizontino": "https://www.fotmob.com/teams/581838/squad/novorizontino",
    "Coritiba": "https://www.fotmob.com/teams/9767/squad/coritiba",
    "Amazonas": "https://www.fotmob.com/teams/1340094/squad/amazonas-fc",
    "Cuiabá": "https://www.fotmob.com/teams/197815/squad/cuiaba",
    "Athletico Paranaense": "https://www.fotmob.com/teams/10273/squad/athletico-paranaense",
    "Atlético GO": "https://www.fotmob.com/teams/165545/overview/atletico-go",
    "Paysandu": "https://www.fotmob.com/teams/6546/squad/paysandu",
    "Volta Redonda": "https://www.fotmob.com/teams/198135/squad/volta-redonda",

    # --- BULGARIA ---
    "Spartak Varna": "https://www.fotmob.com/teams/10145/squad/spartak-varna",
    "Levski Sofia": "https://www.fotmob.com/teams/8632/squad/levski-sofia",
    "Dobrudzha 1919": "https://www.fotmob.com/teams/10140/squad/dobrudzha-dobrich",
    "Slavia Sofia": "https://www.fotmob.com/teams/10134/squad/slavia-sofia",
    "Arda": "https://www.fotmob.com/teams/944173/squad/arda-kardzhali",
    "Botev Vratsa": "https://www.fotmob.com/teams/187880/squad/botev-vratsa",
    "Septemvri Sofia": "https://www.fotmob.com/teams/312976/squad/septemvri-sofia",
    "CSKA Sofia": "https://www.fotmob.com/teams/10144/squad/cska-sofia",
    "Montana": "https://www.fotmob.com/teams/46475/squad/montana",
    "Botev Plovdiv": "https://www.fotmob.com/teams/10131/squad/botev-plovdiv",
    "Cherno More": "https://www.fotmob.com/teams/10141/squad/cherno-more-varna",
    "Beroe": "https://www.fotmob.com/teams/10126/squad/beroe",
    "Lokomotiv Plovdiv": "https://www.fotmob.com/teams/10129/squad/lokomotiv-plovdiv",
    "Lokomotiv Sofia 1929": "https://www.fotmob.com/teams/10128/squad/pfc-lokomotiv-sofia-1929",
    "Ludogorets": "https://www.fotmob.com/teams/210173/squad/ludogorets-razgrad",
    "CSKA 1948 Sofia": "https://www.fotmob.com/teams/10144/squad/cska-sofia",

    # --- CHILE ---
    "Universidad Católica": "https://www.fotmob.com/teams/6458/squad/universidad-catolica",
    "Audax Italiano": "https://www.fotmob.com/teams/4058/squad/audax-italiano",
    "Ñublense": "https://www.fotmob.com/teams/49559/squad/nublense",
    "Unión La Calera": "https://www.fotmob.com/teams/192435/squad/union-la-calera",
    "Coquimbo Unido": "https://www.fotmob.com/teams/4062/squad/coquimbo-unido",
    "Huachipato": "https://www.fotmob.com/teams/4056/squad/huachipato",
    "O'Higgins": "https://www.fotmob.com/teams/6296/squad/ohiggins",
    "Palestino": "https://www.fotmob.com/teams/6455/squad/palestino",
    "Cobresal": "https://www.fotmob.com/teams/4055/squad/cobresal",
    "Deportes Iquique": "https://www.fotmob.com/teams/162904/squad/deportes-iquique",
    "La Serena": "https://www.fotmob.com/teams/1891/squad/la-serena",
    "Colo Colo": "https://www.fotmob.com/teams/7815/squad/colo-colo",
    "Deportes Limache": "https://www.fotmob.com/teams/584840/squad/deportes-limache",
    "Universidad de Chile": "https://www.fotmob.com/teams/6310/squad/universidad-de-chile",
    "Unión Española": "https://www.fotmob.com/teams/7843/squad/union-espanola",

    # --- CHINA ---
    "Zhejiang Professional": "https://www.fotmob.com/teams/51443/squad/zhejiang-professional",
    "Tianjin Tigers": "https://www.fotmob.com/teams/4189/squad/tianjin-jinmen-tiger",
    "Meizhou Hakka": "https://www.fotmob.com/teams/585808/squad/meizhou-hakka",
    "Shanghai Shenhua": "https://www.fotmob.com/teams/6628/squad/shanghai-shenhua",
    "Qingdao West Coast": "https://www.fotmob.com/teams/1283248/squad/qingdao-west-coast",
    "Chengdu Rongcheng": "https://www.fotmob.com/teams/737052/squad/chengdu-rongcheng-fc",
    "Yunnan Yukun": "https://www.fotmob.com/teams/1477056/squad/yunnan-yukun",
    "Beijing Guoan": "https://www.fotmob.com/teams/4177/squad/beijing-guoan",
    "Henan": "https://www.fotmob.com/teams/51442/squad/henan-fc",
    "Shanghai Port": "https://www.fotmob.com/teams/198616/squad/shanghai-port",
    "Qingdao Hainiu": "https://www.fotmob.com/teams/4183/squad/qingdao-hainiu",
    "Dalian Young Boy": "https://www.fotmob.com/teams/1477043/squad/dalian-yingbo",
    "Shandong Taishan": "https://www.fotmob.com/teams/8623/squad/shandong-taishan",
    "Changchun Yatai": "https://www.fotmob.com/teams/6401/squad/changchun-yatai",
    "Shenzhen Peng City": "https://www.fotmob.com/teams/930027/squad/shenzhen-peng-city",
    "Wuhan Three Towns": "https://www.fotmob.com/teams/1029687/squad/wuhan-three-towns",

    # --- COLOMBIA ---
    "Medellín": "https://www.fotmob.com/teams/2528/overview/independiente-medellin",
    "Santa Fe": "https://www.fotmob.com/teams/7818/overview/santa-fe",
    "Junior": "https://www.fotmob.com/teams/2254/overview/junior-fc",
    "Atlético Bucaramanga": "https://www.fotmob.com/teams/4401/overview/bucaramanga",
    "Atlético Nacional": "https://www.fotmob.com/teams/6368/overview/atletico-nacional",
    "Tolima": "https://www.fotmob.com/teams/1894/overview/tolima",
    "América de Cali": "https://www.fotmob.com/teams/10280/overview/america-de-cali",
    "Deportivo Cali": "https://www.fotmob.com/teams/6387/overview/deportivo-cali",
    "Águilas Doradas": "https://www.fotmob.com/teams/193025/overview/aguilas-doradas",
    "Once Caldas": "https://www.fotmob.com/teams/6024/overview/once-caldas",
    "Llaneros": "https://www.fotmob.com/teams/348397/overview/llaneros-fc",
    "La Equidad": "https://www.fotmob.com/teams/47240/overview/internacional-de-bogota",
    "Deportivo Pasto": "https://www.fotmob.com/teams/4405/overview/deportivo-pasto",
    "Millonarios": "https://www.fotmob.com/teams/4403/overview/millonarios",
    "Deportivo Pereira": "https://www.fotmob.com/teams/4404/overview/deportivo-pereira",
    "Unión Magdalena": "https://www.fotmob.com/teams/4408/overview/union-magdalena",
    "Alianza": "https://www.fotmob.com/teams/193029/overview/alianza-fc",
    "Boyacá Chicó": "https://www.fotmob.com/teams/6255/overview/chico-fc",
    "Envigado": "https://www.fotmob.com/teams/4402/overview/envigado",

    # --- CROATIA ---
    "Slaven Belupo": "https://www.fotmob.com/teams/1581/squad/slaven",
    "Gorica": "https://www.fotmob.com/teams/206560/squad/hnk-gorica",
    "Osijek": "https://www.fotmob.com/teams/10157/squad/osijek",
    "Vukovar": "https://www.fotmob.com/teams/45228/squad/vukovar-91",
    "Istra 1961": "https://www.fotmob.com/teams/6038/squad/nk-istra-1961",
    "Dinamo Zagreb": "https://www.fotmob.com/teams/10156/squad/dinamo-zagreb",
    "Rijeka": "https://www.fotmob.com/teams/10162/squad/rijeka",
    "Varaždin": "https://www.fotmob.com/teams/10165/squad/nk-varazdin",
    "Lokomotiva Zagreb": "https://www.fotmob.com/teams/175388/squad/nk-lokomotiva",
    "Hajduk Split": "https://www.fotmob.com/teams/10154/squad/hajduk-split",

    # --- CYPRUS ---
    "Apollon": "https://www.fotmob.com/teams/8003/squad/apollon-limassol",
    "Akritas": "https://www.fotmob.com/teams/184615/squad/akritas-chlorakas",
    "Omonia Aradippou": "https://www.fotmob.com/teams/8044/squad/omonia-nicosia",
    "Ethnikos Achnas": "https://www.fotmob.com/teams/8334/squad/ethnikos-achnas",
    "APOEL": "https://www.fotmob.com/teams/8621/squad/apoel-nicosia",
    "Anorthosis": "https://www.fotmob.com/teams/6243/squad/anorthosis",
    "AEK Larnaca": "https://www.fotmob.com/teams/7797/squad/aek-larnaca",
    "Ypsonas": "https://www.fotmob.com/teams/1075325/squad/krasava-ypsonas-fc",
    "Enosis": "https://www.fotmob.com/teams/4126/squad/enosis-paralimni",
    "Aris": "https://www.fotmob.com/teams/2136/squad/aris-limassol",
    "Omonia Nicosia": "https://www.fotmob.com/teams/8044/squad/omonia-nicosia",
    "Pafos": "https://www.fotmob.com/teams/2137/squad/pafos-fc",
    "AEL": "https://www.fotmob.com/teams/2134/overview/ael-limassol",

    # --- CZECH REPUBLIC ---
    "Jablonec": "https://www.fotmob.com/teams/7758/squad/jablonec",
    "Sparta Praha": "https://www.fotmob.com/teams/10247/squad/sparta-prague",
    "Bohemians 1905": "https://www.fotmob.com/teams/1670/squad/bohemians-1905",
    "Teplice": "https://www.fotmob.com/teams/4721/squad/teplice",
    "Zlín": "https://www.fotmob.com/teams/1860/squad/fc-zlin",
    "Slovan Liberec": "https://www.fotmob.com/teams/10245/overview/slovan-liberec",
    "Hradec Králové": "https://www.fotmob.com/teams/1712/squad/hradec-kralove",
    "Sigma Olomouc": "https://www.fotmob.com/teams/6461/squad/sigma-olomouc",
    "Viktoria Plzeň": "https://www.fotmob.com/teams/6033/squad/viktoria-plzen",
    "Mladá Boleslav": "https://www.fotmob.com/teams/10180/squad/mlada-boleslav",
    "Karviná": "https://www.fotmob.com/teams/143833/squad/karvina",
    "Slovácko": "https://www.fotmob.com/teams/2021/squad/slovacko",
    "Slavia Praha": "https://www.fotmob.com/teams/7787/squad/slavia-prague",
    "Dukla Praha": "https://www.fotmob.com/teams/88657/squad/dukla-praha",
    "Baník Ostrava": "https://www.fotmob.com/teams/6362/squad/banik-ostrava",
    "Pardubice": "https://www.fotmob.com/teams/2406/squad/pardubice",
    "Táborsko": "https://www.fotmob.com/teams/157007/squad/fc-silon-taborsko",
    "Prostějov": "https://www.fotmob.com/teams/358094/squad/sk-prostejov",
    "Viktoria Žižkov": "https://www.fotmob.com/teams/6096/squad/zizkov",
    "Baník Ostrava II": "https://www.fotmob.com/teams/1154238/squad/banik-ostrava-b",
    "Zbrojovka Brno": "https://www.fotmob.com/teams/1673/squad/fc-zbrojovka-brno",
    "Chrudim": "https://www.fotmob.com/teams/279088/squad/mfk-chrudim",
    "Ústí nad Labem": "https://www.fotmob.com/teams/5733/squad/usti-nad-labem",
    "Příbram": "https://www.fotmob.com/teams/1672/squad/pribram",
    "Hanácká": "https://www.fotmob.com/teams/2404/squad/hanacka-slavia-kromeriz",
    "Vlašim": "https://www.fotmob.com/teams/175807/squad/fc-vlasim",
    "Sparta Praha II": "https://www.fotmob.com/teams/132215/squad/sparta-prague-b",
    "Opava": "https://www.fotmob.com/teams/1713/squad/opava",
    "Artis Brno": "https://www.fotmob.com/teams/106189/squad/artis-brno",
    "České Budějovice": "https://www.fotmob.com/teams/7840/squad/sk-dynamo-ceske-budejovice",
    "Slavia Praha II": "https://www.fotmob.com/teams/7787/squad/slavia-prague",
    "Vysočina Jihlava": "https://www.fotmob.com/teams/1949/squad/vysocina-jihlava",

    # --- DENMARK ---
    "OB": "https://www.fotmob.com/teams/8414/squad/ob",
    "København": "https://www.fotmob.com/teams/8391/squad/fc-kobenhavn",
    "Randers": "https://www.fotmob.com/teams/8410/squad/randers-fc",
    "Sønderjyske": "https://www.fotmob.com/teams/8487/squad/sonderjyske",
    "Viborg": "https://www.fotmob.com/teams/9939/squad/viborg",
    "Vejle": "https://www.fotmob.com/teams/8231/squad/vejle-boldklub",
    "Fredericia": "https://www.fotmob.com/teams/8454/squad/fredericia",
    "Brøndby": "https://www.fotmob.com/teams/8595/squad/brondby-if",
    "Silkeborg": "https://www.fotmob.com/teams/8415/squad/silkeborg",
    "Nordsjælland": "https://www.fotmob.com/teams/10202/squad/nordsjaelland",
    "Midtjylland": "https://www.fotmob.com/teams/8113/squad/fc-midtjylland",
    "AGF": "https://www.fotmob.com/teams/8071/squad/agf",
    "Horsens": "https://www.fotmob.com/teams/9814/squad/ac-horsens",
    "Lyngby": "https://www.fotmob.com/teams/9907/squad/lyngby",
    "AaB": "https://www.fotmob.com/teams/8470/squad/aab",
    "Hillerød": "https://www.fotmob.com/teams/9940/squad/hillerod",
    "Hobro": "https://www.fotmob.com/teams/9950/squad/hobro",
    "Middelfart": "https://www.fotmob.com/teams/9969/squad/middelfart",
    "B.93": "https://www.fotmob.com/teams/8453/squad/b-93",
    "Esbjerg": "https://www.fotmob.com/teams/8285/squad/esbjerg-fb",
    "Aarhus Fremad": "https://www.fotmob.com/teams/8109/squad/aarhus-fremad",
    "Hvidovre": "https://www.fotmob.com/teams/10240/squad/hvidovre",
    "Kolding IF": "https://www.fotmob.com/teams/6308/squad/kolding-if",
    "HB Køge": "https://www.fotmob.com/teams/8289/squad/hb-koge",

    # --- ECUADOR ---
    "Libertad": "https://www.fotmob.com/teams/1345405/squad/libertad",
    "Deportivo Cuenca": "https://www.fotmob.com/teams/4144/squad/deportivo-cuenca",
    "Orense": "https://www.fotmob.com/teams/1014174/squad/orense",
    "Emelec": "https://www.fotmob.com/teams/1850/squad/emelec",
    "Macará": "https://www.fotmob.com/teams/6609/squad/csd-macara",
    "Aucas": "https://www.fotmob.com/teams/6608/squad/aucas",
    "Delfin": "https://www.fotmob.com/teams/519457/squad/delfin",
    "LDU Quito": "https://www.fotmob.com/teams/6721/squad/ldu-de-quito",
    "Barcelona": "https://www.fotmob.com/teams/6453/squad/barcelona-sc",
    "Independiente del Valle": "https://www.fotmob.com/teams/192875/squad/independiente-del-valle",
    "Técnico Universitario": "https://www.fotmob.com/teams/113054/squad/tecnico-universitario",
    "Manta": "https://www.fotmob.com/teams/162922/squad/manta",
    "Vinotinto de Ecuador": "https://www.fotmob.com/teams/1446544/squad/vinotinto-del-ecuador",
    "El Nacional": "https://www.fotmob.com/teams/6612/squad/el-nacional",
    "Mushuc Runa": "https://www.fotmob.com/teams/304929/squad/mushuc-runa",

    # --- ESTONIA ---
    "Pärnu JK Vaprus": "https://www.fotmob.com/teams/828265/squad/parnu-jk-vaprus",
    "Nõmme Kalju": "https://www.fotmob.com/teams/112484/squad/nomme-jk-kalju",
    "Kuressaare": "https://www.fotmob.com/teams/4146/squad/fc-kuressaare",
    "Flora": "https://www.fotmob.com/teams/8155/squad/flora-tallinn",
    "Harju JK": "https://www.fotmob.com/teams/673053/squad/harju-jalgpallikool",
    "Tartu Tammeka": "https://www.fotmob.com/teams/4147/squad/tammeka",
    "Trans": "https://www.fotmob.com/teams/2252/squad/narva-trans",
    "Levadia": "https://www.fotmob.com/teams/1588/squad/fci-levadia",
    "Paide": "https://www.fotmob.com/teams/163540/squad/paide-linnameeskond",
    "Tallinna Kalev": "https://www.fotmob.com/teams/49578/squad/tallinna-kalev",

    # --- FINLAND ---
    "Inter Turku": "https://www.fotmob.com/teams/6550/squad/fc-inter-turku",
    "Ilves": "https://www.fotmob.com/teams/162146/squad/ilves",
    "SJK": "https://www.fotmob.com/teams/162162/squad/sjk",
    "HJK": "https://www.fotmob.com/teams/9861/squad/hjk",
    "KTP": "https://www.fotmob.com/teams/6701/squad/fc-ktp",
    "Gnistan": "https://www.fotmob.com/teams/2361/squad/if-gnistan",
    "VPS": "https://www.fotmob.com/teams/6597/squad/vps",
    "KuPS": "https://www.fotmob.com/teams/1693/squad/kups",
    "Jaro": "https://www.fotmob.com/teams/8473/squad/ff-jaro",
    "Mariehamn": "https://www.fotmob.com/teams/6634/squad/ifk-mariehamn",
    "Oulu": "https://www.fotmob.com/teams/4449/squad/ac-oulu",
    "Haka": "https://www.fotmob.com/teams/7870/squad/haka",

    # --- FRANCE ---
    "Nantes": "https://www.fotmob.com/teams/9830/squad/nantes",
    "Toulouse": "https://www.fotmob.com/teams/9941/squad/toulouse",
    "Lens": "https://www.fotmob.com/teams/8588/squad/lens",
    "Le Havre": "https://www.fotmob.com/teams/9746/squad/le-havre",
    "Rennes": "https://www.fotmob.com/teams/9851/squad/rennes",
    "Angers SCO": "https://www.fotmob.com/teams/8121/squad/angers",
    "Metz": "https://www.fotmob.com/teams/8550/squad/metz",
    "Lorient": "https://www.fotmob.com/teams/8689/squad/lorient",
    "Nice": "https://www.fotmob.com/teams/9831/squad/nice",
    "Paris": "https://www.fotmob.com/teams/6379/squad/paris-fc",
    "Strasbourg": "https://www.fotmob.com/teams/9848/squad/strasbourg",
    "Brest": "https://www.fotmob.com/teams/8521/squad/brest",
    "Olympique Lyonnais": "https://www.fotmob.com/teams/9748/squad/lyon",
    "Lille": "https://www.fotmob.com/teams/8639/squad/lille",
    "PSG": "https://www.fotmob.com/teams/9847/squad/paris-saint-germain",
    "Monaco": "https://www.fotmob.com/teams/9829/squad/monaco",
    "Auxerre": "https://www.fotmob.com/teams/8583/squad/auxerre",
    "Olympique Marseille": "https://www.fotmob.com/teams/8592/squad/marseille",
    "Guingamp": "https://www.fotmob.com/teams/9747/squad/guingamp",
    "Amiens SC": "https://www.fotmob.com/teams/8587/squad/amiens",
    "Reims": "https://www.fotmob.com/teams/9837/squad/reims",
    "Saint-Étienne": "https://www.fotmob.com/teams/9853/squad/saint-etienne",
    "Le Mans": "https://www.fotmob.com/teams/8682/squad/le-mans",
    "Troyes": "https://www.fotmob.com/teams/10242/squad/troyes",
    "Rodez": "https://www.fotmob.com/teams/4120/squad/rodez",
    "Annecy": "https://www.fotmob.com/teams/293352/squad/annecy-fc",
    "Red Star": "https://www.fotmob.com/teams/6390/squad/red-star",
    "Clermont": "https://www.fotmob.com/teams/8311/squad/clermont-foot",
    "Laval": "https://www.fotmob.com/teams/7853/squad/laval",
    "Grenoble": "https://www.fotmob.com/teams/9855/squad/grenoble",
    "Dunkerque": "https://www.fotmob.com/teams/47214/squad/dunkerque",
    "Montpellier": "https://www.fotmob.com/teams/10249/squad/montpellier",
    "Boulogne": "https://www.fotmob.com/teams/4170/squad/boulogne",
    "Bastia": "https://www.fotmob.com/teams/7794/squad/sc-bastia",
    "Nancy": "https://www.fotmob.com/teams/8481/squad/nancy",
    "Pau": "https://www.fotmob.com/teams/6355/squad/pau",
    "Villefranche": "https://www.fotmob.com/teams/161694/squad/villefranche-beaujolais",
    "Bourg-en-Bresse": "https://www.fotmob.com/teams/6246/squad/bourg-en-bresse-peronnas",
    "Le Puy F.43 Auvergne": "https://www.fotmob.com/teams/293257/squad/le-puy",
    "Aubagne": "https://www.fotmob.com/teams/293443/squad/sc-aubagne-air-bel",
    "Châteauroux": "https://www.fotmob.com/teams/9854/squad/chateauroux",
    "Rouen": "https://www.fotmob.com/teams/8582/squad/rouen",
    "Caen": "https://www.fotmob.com/teams/7819/squad/caen",
    "Concarneau": "https://www.fotmob.com/teams/47207/squad/concarneau",
    "Dijon": "https://www.fotmob.com/teams/9836/squad/dijon",
    "Stade Briochin": "https://www.fotmob.com/teams/685213/squad/stade-briochin",
    "Fleury 91 FC": "https://www.fotmob.com/teams/238687/squad/fc-fleury-91",
    "Orléans": "https://www.fotmob.com/teams/47211/squad/orleans",
    "Versailles": "https://www.fotmob.com/teams/191111/squad/versailles",
    "Valenciennes": "https://www.fotmob.com/teams/9873/squad/valenciennes",
    "Sochaux": "https://www.fotmob.com/teams/9874/squad/sochaux",
    "Quevilly Rouen": "https://www.fotmob.com/teams/2517/squad/quevilly",
    "Paris 13 Atletico": "https://www.fotmob.com/teams/238671/squad/paris-13-atletico",

    # --- GEORGIA ---
    "Torpedo Kutaisi": "https://www.fotmob.com/teams/2216/overview/torpedo-kutaisi",
    "Gagra": "https://www.fotmob.com/teams/154186/overview/fc-gagra",
    "Iberia 1999": "https://www.fotmob.com/teams/480291/overview/iberia-1999",
    "Dila": "https://www.fotmob.com/teams/2217/overview/dila-gori",
    "Telavi": "https://www.fotmob.com/teams/1168646/overview/fc-telavi",
    "Samgurali": "https://www.fotmob.com/teams/316432/overview/fc-samgurali-tskhaltubo",
    "Dinamo Batumi": "https://www.fotmob.com/teams/6193/overview/dinamo-batumi",
    "Gareji": "https://www.fotmob.com/teams/1230631/overview/fc-gareji-1960",
    "Dinamo Tbilisi": "https://www.fotmob.com/teams/7755/overview/dinamo-tbilisi",
    "Kolkheti Poti": "https://www.fotmob.com/teams/2218/overview/kolkheti-1913-poti",

    # --- GERMANY ---
    "Köln": "https://www.fotmob.com/teams/8722/squad/1-fc-koln",
    "Wolfsburg": "https://www.fotmob.com/teams/8721/squad/wolfsburg",
    "Union Berlin": "https://www.fotmob.com/teams/8149/squad/union-berlin",
    "Augsburg": "https://www.fotmob.com/teams/8406/squad/augsburg",
    "Mainz 05": "https://www.fotmob.com/teams/9905/squad/mainz-05",
    "Hamburger SV": "https://www.fotmob.com/teams/9790/squad/hamburger-sv",
    "Bayer Leverkusen": "https://www.fotmob.com/teams/8178/squad/bayer-leverkusen",
    "Stuttgart": "https://www.fotmob.com/teams/10269/squad/vfb-stuttgart",
    "Freiburg": "https://www.fotmob.com/teams/8358/squad/freiburg",
    "Hoffenheim": "https://www.fotmob.com/teams/8226/squad/hoffenheim",
    "Borussia Dortmund": "https://www.fotmob.com/teams/9789/squad/borussia-dortmund",
    "Borussia M'gladbach": "https://www.fotmob.com/teams/9788/squad/borussia-monchengladbach",
    "St. Pauli": "https://www.fotmob.com/teams/8152/squad/st-pauli",
    "RB Leipzig": "https://www.fotmob.com/teams/178475/squad/rb-leipzig",
    "Heidenheim": "https://www.fotmob.com/teams/94937/squad/fc-heidenheim",
    "Eintracht Frankfurt": "https://www.fotmob.com/teams/9810/squad/eintracht-frankfurt",
    "Werder Bremen": "https://www.fotmob.com/teams/8697/squad/werder-bremen",
    "Bayern München": "https://www.fotmob.com/teams/9823/squad/bayern-munchen",
    "Eintracht Braunschweig": "https://www.fotmob.com/teams/9776/squad/eintracht-braunschweig",
    "Schalke 04": "https://www.fotmob.com/teams/10189/squad/schalke-04",
    "Paderborn": "https://www.fotmob.com/teams/8460/squad/paderborn",
    "Magdeburg": "https://www.fotmob.com/teams/8188/squad/magdeburg",
    "Arminia Bielefeld": "https://www.fotmob.com/teams/9912/squad/arminia-bielefeld",
    "Hannover 96": "https://www.fotmob.com/teams/9904/squad/hannover-96",
    "Holstein Kiel": "https://www.fotmob.com/teams/8150/squad/holstein-kiel",
    "Nürnberg": "https://www.fotmob.com/teams/8165/squad/1-fc-nurnberg",
    "Fortuna Düsseldorf": "https://www.fotmob.com/teams/8194/squad/fortuna-dusseldorf",
    "Elversberg": "https://www.fotmob.com/teams/8232/squad/elversberg",
    "Bochum": "https://www.fotmob.com/teams/9911/squad/bochum",
    "Hertha BSC": "https://www.fotmob.com/teams/8177/squad/hertha-bsc",
    "Darmstadt 98": "https://www.fotmob.com/teams/8262/squad/darmstadt",
    "Kaiserslautern": "https://www.fotmob.com/teams/8350/squad/kaiserslautern",
    "Preußen Münster": "https://www.fotmob.com/teams/8171/squad/preussen-munster",
    "Karlsruher SC": "https://www.fotmob.com/teams/8295/squad/karlsruher-sc",
    "Dynamo Dresden": "https://www.fotmob.com/teams/8480/squad/dynamo-dresden",
    "Greuther Fürth": "https://www.fotmob.com/teams/8357/squad/greuther-furth",
    "Jahn Regensburg": "https://www.fotmob.com/teams/7789/squad/jahn-regensburg",
    "Alemannia Aachen": "https://www.fotmob.com/teams/8396/squad/alemannia-aachen",
    "1860 München": "https://www.fotmob.com/teams/9753/squad/1860-munchen",
    "Ingolstadt": "https://www.fotmob.com/teams/8234/squad/ingolstadt",
    "Rot-Weiss Essen": "https://www.fotmob.com/teams/8296/squad/rw-essen",
    "Hansa Rostock": "https://www.fotmob.com/teams/8294/squad/hansa-rostock",
    "Erzgebirge Aue": "https://www.fotmob.com/teams/8319/squad/erzgebirge-aue",
    "Verl": "https://www.fotmob.com/teams/7783/squad/sc-verl",
    "MSV Duisburg": "https://www.fotmob.com/teams/8293/squad/msv-duisburg",
    "Osnabrück": "https://www.fotmob.com/teams/9775/squad/vfl-osnabruck",
    "Wehen Wiesbaden": "https://www.fotmob.com/teams/8196/squad/wehen-wiesbaden",
    "Energie Cottbus": "https://www.fotmob.com/teams/8398/squad/energie-cottbus",
    "Havelse": "https://www.fotmob.com/teams/89338/squad/tsv-havelse",
    "Saarbrücken": "https://www.fotmob.com/teams/8271/squad/saarbrucken",
    "Waldhof Mannheim": "https://www.fotmob.com/teams/9743/squad/waldhof-mannheim",
    "Viktoria Köln": "https://www.fotmob.com/teams/276267/squad/viktoria-koln-1904",
    "Ulm": "https://www.fotmob.com/teams/8201/squad/ulm",
    "Hoffenheim II": "https://www.fotmob.com/teams/94940/squad/hoffenheim-ii",
    "Schweinfurt": "https://www.fotmob.com/teams/7780/squad/fc-schweinfurt",
    "Stuttgart II": "https://www.fotmob.com/teams/8458/squad/vfb-stuttgart-ii",
    "Sonnenhof Großaspach": "https://www.fotmob.com/teams/94941/overview/sonnenhof-grossaspach",
    "Sandhausen": "https://www.fotmob.com/teams/8086/overview/sandhausen",
    "Kickers Offenbach": "https://www.fotmob.com/teams/8407/overview/kickers-offenbach",
    "Freiburg II": "https://www.fotmob.com/teams/6594/overview/freiburg-ii",
    "Hessen Kassel": "https://www.fotmob.com/teams/8253/overview/hessen-kassel",
    "Astoria Walldorf": "https://www.fotmob.com/teams/94938/overview/fca-walldorf",
    "Homburg": "https://www.fotmob.com/teams/1734/overview/homburg",
    "Barockstadt Fulda-Lehnerz": "https://www.fotmob.com/teams/465626/overview/sg-barockstadt-fulda-lehnerz",
    "Steinbach": "https://www.fotmob.com/teams/557592/overview/tsv-steinbach",
    "Stuttgarter Kickers": "https://www.fotmob.com/teams/8195/overview/stuttgarter-kickers",
    "FSV Frankfurt": "https://www.fotmob.com/teams/88885/overview/fsv-frankfurt",
    "SGV Freiberg": "https://www.fotmob.com/teams/94935/overview/freiberg",
    "Eintracht Trier": "https://www.fotmob.com/teams/7774/overview/eintracht-trier",
    "Bayern Alzenau": "https://www.fotmob.com/teams/95039/overview/bayern-alzenau",
    "Bahlinger SC": "https://www.fotmob.com/teams/2393/overview/bahlinger-sc",
    "Mainz 05 II": "https://www.fotmob.com/teams/8397/overview/mainz-05-ii",
    "Schott Mainz": "https://www.fotmob.com/teams/555501/overview/tsv-schott-mainz",
    "Balingen": "https://www.fotmob.com/teams/145498/overview/tsg-balingen",
    "Rot-Weiß Oberhausen": "https://www.fotmob.com/teams/7782/overview/oberhausen",
    "Fortuna Köln": "https://www.fotmob.com/teams/7786/overview/fortuna-koln",
    "Gütersloh": "https://www.fotmob.com/teams/6200/overview/fc-gutersloh",
    "FC Bocholt": "https://www.fotmob.com/teams/557692/overview/fc-bocholt",
    "Sportfreunde Siegen": "https://www.fotmob.com/teams/9757/overview/sportfreunde-siegen",
    "Borussia Dortmund II": "https://www.fotmob.com/teams/8395/overview/borussia-dortmund-ii",
    "Fortuna Düsseldorf II": "https://www.fotmob.com/teams/95052/overview/fortuna-dusseldorf-ii",
    "Velbert": "https://www.fotmob.com/teams/2564/overview/velbert",
    "Schalke 04 II": "https://www.fotmob.com/teams/8198/overview/schalke-04-ii",
    "Wuppertaler SV": "https://www.fotmob.com/teams/8142/overview/wuppertal",
    "Köln II": "https://www.fotmob.com/teams/8459/overview/fc-koln-ii",
    "Paderborn II": "https://www.fotmob.com/teams/657648/overview/sc-paderborn-07-ii",
    "Bonner SC": "https://www.fotmob.com/teams/95047/overview/bonner-sc",
    "Wiedenbrück": "https://www.fotmob.com/teams/95106/overview/sc-wiedenbruck",
    "Rödinghausen": "https://www.fotmob.com/teams/465376/overview/sv-rodinghausen",
    "Borussia M'gladbach II": "https://www.fotmob.com/teams/8278/overview/borussia-monchengladbach-ii",
    "Bochum II": "https://www.fotmob.com/teams/8200/overview/bochum-ii",
    "Sportfreunde Lotte": "https://www.fotmob.com/teams/95103/overview/sportfreunde-lotte",

    # --- GREECE ---
    "Levadiakos": "https://www.fotmob.com/teams/4493/squad/levadiakos",
    "Panetolikos FC": "https://www.fotmob.com/teams/162386/squad/panetolikos",
    "Olympiacos Piraeus": "https://www.fotmob.com/teams/8638/squad/olympiacos",
    "AEK Athens": "https://www.fotmob.com/teams/8563/squad/aek-athens",
    "Atromitos": "https://www.fotmob.com/teams/10187/squad/atromitos",
    "Volos NFC": "https://www.fotmob.com/teams/885256/squad/nfc-volos",
    "Kifissia": "https://www.fotmob.com/teams/488099/squad/kifisia-fc",
    "PAOK": "https://www.fotmob.com/teams/8619/squad/paok-thessaloniki",
    "Panserraikos": "https://www.fotmob.com/teams/104814/squad/panserraikos-fc",
    "OFI": "https://www.fotmob.com/teams/7753/squad/ofi-crete",
    "Asteras Tripolis": "https://www.fotmob.com/teams/80654/squad/asteras-tripolis",
    "Larissa": "https://www.fotmob.com/teams/8120/squad/ae-larissa",
    "Panathinaikos": "https://www.fotmob.com/teams/10200/squad/panathinaikos",

    # --- HUNGARY ---
    "Zalaegerszegi TE": "https://www.fotmob.com/teams/1667/squad/zalaegerszeg",
    "Debrecen": "https://www.fotmob.com/teams/8369/squad/debrecen",
    "Várda SE": "https://www.fotmob.com/teams/465382/overview/kisvarda",
    "Puskás FC": "https://www.fotmob.com/teams/355346/squad/puskas-fc-academy",
    "Diósgyőr": "https://www.fotmob.com/teams/2476/squad/diosgyori-vtk",
    "MTK": "https://www.fotmob.com/teams/7778/squad/mtk-budapest",
    "Újpest": "https://www.fotmob.com/teams/8043/squad/ujpest",
    "Kazincbarcika": "https://www.fotmob.com/teams/2280/squad/kazincbarcikai-bsc",
    "Győri ETO": "https://www.fotmob.com/teams/5755/squad/gyori-eto",
    "Ferencváros": "https://www.fotmob.com/teams/8222/squad/ferencvaros",
    "Paksi FC": "https://www.fotmob.com/teams/7986/squad/paksi-se",
    "Nyíregyháza Spartacus": "https://www.fotmob.com/teams/2035/squad/nyiregyhaza-spartacus-fc",

    # --- ICELAND ---
    "Afturelding": "https://www.fotmob.com/teams/163251/squad/afturelding",
    "Stjarnan": "https://www.fotmob.com/teams/6343/overview/stjarnan",
    "Breidablik": "https://www.fotmob.com/teams/8332/squad/breidablik",
    "Vestri": "https://www.fotmob.com/teams/750462/overview/vestri",
    "ÍA": "https://www.fotmob.com/teams/8004/squad/ia-akranes",
    "Fram": "https://www.fotmob.com/teams/6291/overview/fram-reykjavik",
    "KA": "https://www.fotmob.com/teams/2165/squad/ka-akureyri",
    "FH": "https://www.fotmob.com/teams/8151/squad/fh-hafnarfjordur",
    "Valur": "https://www.fotmob.com/teams/8064/overview/valur",
    "KR": "https://www.fotmob.com/teams/8130/overview/kr-reykjavik",
    "ÍBV": "https://www.fotmob.com/teams/8299/squad/ibv-vestmannaeyjar",
    "Víkingur Reykjavík": "https://www.fotmob.com/teams/6017/squad/vikingur-reykjavik",

    # --- ISRAEL ---
    "Ironi Kiryat Shmona": "https://www.fotmob.com/teams/2095/squad/hapoel-ironi-kiryat-shmona",
    "Hapoel Jerusalem": "https://www.fotmob.com/teams/459591/squad/hapoel-jerusalem-fc",
    "Ashdod": "https://www.fotmob.com/teams/6203/squad/fc-ashdod",
    "Hapoel Petah Tikva": "https://www.fotmob.com/teams/9755/squad/hapoel-petah-tikva",
    "Hapoel Be'er Sheva": "https://www.fotmob.com/teams/9754/squad/hapoel-beer-sheva",
    "Beitar Jerusalem": "https://www.fotmob.com/teams/8173/squad/beitar-jerusalem",
    "Bnei Sakhnin": "https://www.fotmob.com/teams/8718/squad/bnei-sakhnin",
    "Hapoel Haifa": "https://www.fotmob.com/teams/8301/squad/hapoel-haifa",
    "Hapoel Tel Aviv": "https://www.fotmob.com/teams/10181/squad/hapoel-tel-aviv",
    "Maccabi Tel Aviv": "https://www.fotmob.com/teams/7855/squad/maccabi-tel-aviv",
    "Maccabi Netanya": "https://www.fotmob.com/teams/1832/squad/maccabi-netanya",
    "Ironi Tiberias": "https://www.fotmob.com/teams/543580/squad/ironi-tiberias",
    "Maccabi Haifa": "https://www.fotmob.com/teams/10185/squad/maccabi-haifa",
    "Maccabi Bnei Raina": "https://www.fotmob.com/teams/1121750/squad/maccabi-bnei-raina",
    "Maccabi Petah Tikva": "https://www.fotmob.com/teams/9755/squad/hapoel-petah-tikva",
    "Hapoel Raanana": "https://www.fotmob.com/teams/2096/overview/hapoel-raanana",
    "Hapoel Kfar Saba": "https://www.fotmob.com/teams/6280/overview/hapoel-kfar-saba",
    "Hapoel Ramat Gan": "https://www.fotmob.com/teams/89753/overview/hapoel-ramat-gan",
    "Maccabi Herzliya": "https://www.fotmob.com/teams/2097/overview/maccabi-herzliya",
    "Hapoel Afula": "https://www.fotmob.com/teams/426452/overview/hapoel-afula",
    "Kfar Kasem": "https://www.fotmob.com/teams/752833/overview/sc-kafr-qasim",
    "Hapoel Acre": "https://www.fotmob.com/teams/426452/overview/hapoel-afula",
    "Hapoel Nof HaGalil": "https://www.fotmob.com/teams/4125/overview/hapoel-nof-hagalil",
    "Ironi Modi'in": "https://www.fotmob.com/teams/1691612/overview/ironi-modiin",
    "Bnei Yehuda": "https://www.fotmob.com/teams/2215/overview/bnei-yehuda-tel-aviv",
    "Hapoel Kfar Shalem": "https://www.fotmob.com/teams/1177310/overview/hapoel-kfar-shalem",
    "Kiryat Yam": "https://www.fotmob.com/teams/1691614/overview/kiryat-yam",
    "Hapoel Rishon LeZion": "https://www.fotmob.com/teams/1831/overview/hapoel-rishon-lezion",
    "Maccabi Kabilio Jaffa": "https://www.fotmob.com/teams/196257/overview/maccabi-kabilio-jaffa",
    "Hapoel Hadera": "https://www.fotmob.com/teams/857444/overview/hapoel-hadera",

    # --- ITALY ---
    "Fiorentina": "https://www.fotmob.com/teams/8535/squad/fiorentina",
    "Genoa": "https://www.fotmob.com/teams/10233/squad/genoa",
    "Cremonese": "https://www.fotmob.com/teams/7801/squad/cremonese",
    "Juventus": "https://www.fotmob.com/teams/9885/squad/juventus",
    "Roma": "https://www.fotmob.com/teams/8686/squad/roma",
    "Cagliari": "https://www.fotmob.com/teams/8529/squad/cagliari",
    "Lazio": "https://www.fotmob.com/teams/8543/squad/lazio",
    "Pisa": "https://www.fotmob.com/teams/6479/squad/pisa",
    "Atalanta": "https://www.fotmob.com/teams/8524/squad/atalanta",
    "Udinese": "https://www.fotmob.com/teams/8600/squad/udinese",
    "Sassuolo": "https://www.fotmob.com/teams/7943/squad/sassuolo",
    "Napoli": "https://www.fotmob.com/teams/9875/squad/napoli",
    "Lecce": "https://www.fotmob.com/teams/9888/squad/lecce",
    "Hellas Verona": "https://www.fotmob.com/teams/9876/squad/hellas-verona",
    "Como": "https://www.fotmob.com/teams/10171/squad/como",
    "Milan": "https://www.fotmob.com/teams/8564/squad/milan",
    "Torino": "https://www.fotmob.com/teams/9804/squad/torino",
    "Parma": "https://www.fotmob.com/teams/10167/squad/parma",
    "Internazionale": "https://www.fotmob.com/teams/8636/squad/inter",
    "Bologna": "https://www.fotmob.com/teams/9857/squad/bologna",
    "Bari": "https://www.fotmob.com/teams/9976/squad/bari",
    "Catanzaro": "https://www.fotmob.com/teams/10168/squad/catanzaro",
    "Modena": "https://www.fotmob.com/teams/9887/squad/modena",
    "Carrarese": "https://www.fotmob.com/teams/6488/squad/carrarese",
    "Juve Stabia": "https://www.fotmob.com/teams/6106/squad/juve-stabia",
    "Pescara": "https://www.fotmob.com/teams/9878/squad/pescara",
    "Frosinone": "https://www.fotmob.com/teams/9891/squad/frosinone",
    "Cesena": "https://www.fotmob.com/teams/584022/squad/cesena",
    "Venezia": "https://www.fotmob.com/teams/7881/squad/venezia",
    "Mantova": "https://www.fotmob.com/teams/9889/squad/mantova",
    "Empoli": "https://www.fotmob.com/teams/8534/squad/empoli",
    "Reggiana": "https://www.fotmob.com/teams/6500/squad/reggiana",
    "Monza": "https://www.fotmob.com/teams/6504/squad/monza",
    "Palermo": "https://www.fotmob.com/teams/8540/squad/palermo",
    "Spezia": "https://www.fotmob.com/teams/9881/squad/spezia",
    "Padova": "https://www.fotmob.com/teams/583944/squad/padova",
    "Virtus Entella": "https://www.fotmob.com/teams/208932/squad/virtus-entella",
    "Sampdoria": "https://www.fotmob.com/teams/9882/squad/sampdoria",
    "Südtirol": "https://www.fotmob.com/teams/189475/squad/sudtirol",
    "Avellino": "https://www.fotmob.com/teams/6722/squad/avellino",
    "Salernitana": "https://www.fotmob.com/teams/6480/overview/salernitana",
    "Pineto": "https://www.fotmob.com/teams/770928/overview/pineto",
    "Cavese": "https://www.fotmob.com/teams/6063/overview/cavese",
    "Catania": "https://www.fotmob.com/teams/8530/overview/catania",
    "Juventus Next Gen": "https://www.fotmob.com/teams/956184/overview/juventus-next-gen",
    "Perugia": "https://www.fotmob.com/teams/8685/overview/perugia",
    "Trapani": "https://www.fotmob.com/teams/208936/overview/trapani",
    "Ternana": "https://www.fotmob.com/teams/6457/overview/ternana",
    "Vis Pesaro": "https://www.fotmob.com/teams/6049/overview/vis-pesaro",
    "Brescia": "https://www.fotmob.com/teams/189481/overview/union-brescia",
    "Virtus Verona": "https://www.fotmob.com/teams/474519/overview/virtus-verona",
    "Forlì": "https://www.fotmob.com/teams/6071/overview/forli",
    "Lecco": "https://www.fotmob.com/teams/6512/overview/lecco",
    "Ascoli": "https://www.fotmob.com/teams/8522/overview/ascoli",
    "Vicenza": "https://www.fotmob.com/teams/145007/overview/lr-vicenza",
    "Pontedera": "https://www.fotmob.com/teams/145016/overview/pontedera",
    "Arzignano Valchiampo": "https://www.fotmob.com/teams/583958/overview/arzignanochiampo",
    "Ospitaletto": "https://www.fotmob.com/teams/6494/overview/ospitaletto",
    "Casarano": "https://www.fotmob.com/teams/6460/overview/casarano",
    "Audace Cerignola": "https://www.fotmob.com/teams/867620/overview/audace-cerignola",
    "Picerno": "https://www.fotmob.com/teams/674807/overview/az-picerno",
    "Casertana": "https://www.fotmob.com/teams/277990/overview/casertana",
    "Sorrento": "https://www.fotmob.com/teams/88998/overview/sorrento",
    "Arezzo": "https://www.fotmob.com/teams/9849/overview/arezzo",
    "Ravenna": "https://www.fotmob.com/teams/8545/overview/ravenna",
    "Novara": "https://www.fotmob.com/teams/6269/overview/novara",
    "Latina": "https://www.fotmob.com/teams/212660/overview/latina",
    "Giugliano": "https://www.fotmob.com/teams/6040/overview/giugliano",
    "Guidonia Montecelio": "https://www.fotmob.com/teams/1667898/overview/guidonia-montecelio",
    "Crotone": "https://www.fotmob.com/teams/9884/overview/crotone",
    "Alcione Milano": "https://www.fotmob.com/teams/655295/overview/alcione",
    "Benevento": "https://www.fotmob.com/teams/6266/overview/benevento",
    "Cosenza": "https://www.fotmob.com/teams/6456/overview/cosenza",
    "Bra": "https://www.fotmob.com/teams/474518/overview/bra",
    "Foggia": "https://www.fotmob.com/teams/6466/overview/foggia",
    "Pro Patria": "https://www.fotmob.com/teams/6498/overview/pro-patria",
    "Triestina": "https://www.fotmob.com/teams/9872/overview/triestina",
    "GIANA Erminio": "https://www.fotmob.com/teams/568741/overview/giana-erminio",
    "Siracusa": "https://www.fotmob.com/teams/674812/overview/siracusa-calcio",
    "Renate": "https://www.fotmob.com/teams/177522/overview/renate",
    "Pro Vercelli": "https://www.fotmob.com/teams/189486/overview/pro-vercelli",
    "Campobasso": "https://www.fotmob.com/teams/212658/overview/campobasso",
    "Monopoli": "https://www.fotmob.com/teams/189506/overview/monopoli",
    "Carpi": "https://www.fotmob.com/teams/208931/overview/carpi",
    "Lumezzane": "https://www.fotmob.com/teams/6452/overview/lumezzane",
    "Pianese": "https://www.fotmob.com/teams/584069/overview/pianese",
    "Team Altamura": "https://www.fotmob.com/teams/867623/overview/team-altamura",
    "Internazionale II": "https://www.fotmob.com/teams/1790497/overview/inter-u23",
    "Dolomiti Bellunesi": "https://www.fotmob.com/teams/1295924/overview/dolomiti-bellunesi",
    "Sambenedettese": "https://www.fotmob.com/teams/8482/overview/sambenedettese",
    "Gubbio": "https://www.fotmob.com/teams/6061/overview/gubbio",
    "Pergolettese": "https://www.fotmob.com/teams/474521/overview/pergolettese",
    "Cittadella": "https://www.fotmob.com/teams/6485/overview/cittadella",
    "Livorno": "https://www.fotmob.com/teams/8537/overview/livorno",
    "Trento": "https://www.fotmob.com/teams/6097/overview/trento",
    "AlbinoLeffe": "https://www.fotmob.com/teams/9832/overview/albinoleffe",
    "Torres": "https://www.fotmob.com/teams/7856/overview/torres",
    "Atalanta U23": "https://www.fotmob.com/teams/1524591/overview/atalanta-u23",
    "Potenza": "https://www.fotmob.com/teams/6099/overview/potenza",
    "Rimini": "https://www.fotmob.com/teams/9886/overview/rimini",

    # --- JAPAN ---
    "Kashima Antlers": "",
    "Nagoya Grampus": "",
    "Vissel Kobe": "",
    "Sanfrecce Hiroshima": "",
    "Machida Zelvia": "",
    "Gamba Osaka": "",
    "Tokyo Verdy": "",
    "Kashiwa Reysol": "",
    "Shimizu S-Pulse": "",
    "Yokohama": "",
    "Kyoto Sanga": "",
    "Fagiano Okayama": "",
    "Avispa Fukuoka": "",
    "Urawa Reds": "",
    "Kawasaki Frontale": "",
    "Albirex Niigata": "",
    "Cerezo Osaka": "",
    "Shonan Bellmare": "",
    "Tokyo": "",
    "Yokohama F. Marinos": "",
    "JEF United": "",
    "Tokushima Vortis": "",
    "Fujieda MYFC": "",
    "Sagan Tosu": "",
    "Mito Hollyhock": "",
    "V-Varen Nagasaki": "",
    "RB Omiya Ardija": "",
    "Blaublitz Akita": "",
    "Renofa Yamaguchi": "",
    "Iwaki": "",
    "Vegalta Sendai": "",
    "Kataller Toyama": "",
    "Roasso Kumamoto": "",
    "Oita Trinita": "",
    "Consadole Sapporo": "",
    "Júbilo Iwata": "",
    "Imabari": "",
    "Ventforet Kofu": "",
    "Ehime": "",
    "Montedio Yamagata": "",

    # --- KAZAKHSTAN ---
    "Kaisar": "",
    "Zhenys": "",
    "Ulytau": "",
    "Yelimay Semey": "",
    "Ordabasy": "",
    "Astana": "",
    "Zhetysu": "",
    "Tobol": "",
    "Okzhetpes": "",
    "Aktobe": "",
    "Kairat": "",
    "Atyrau": "",
    "Kyzyl-Zhar": "",
    "Turan Turkistan": "",

    # --- SOUTH KOREA ---
    "Jeonbuk Motors": "",
    "Seoul": "",
    "Gwangju": "",
    "Pohang Steelers": "",
    "Daejeon Citizen": "",
    "Daegu": "",
    "Anyang": "",
    "Ulsan Hyundai": "",
    "Jeju SK": "",
    "Suwon": "",
    "Gangwon": "",
    "Gimcheon Sangmu": "",
    "Incheon United": "",
    "Bucheon 1995": "",
    "Seongnam": "",
    "Chungbuk Cheongju": "",
    "Jeonnam Dragons": "",
    "Busan I'Park": "",
    "Chungnam Asan": "",
    "Ansan Greeners": "",
    "Gyeongnam": "",
    "Gimpo Citizen": "",
    "Hwaseong": "",
    "Seoul E-Land": "",
    "Suwon Bluewings": "",
    "Cheonan City": "",

    # --- KOSOVO ---
    "Gjilani": "",
    "Prishtina e Re": "",
    "Llapi": "",
    "Prishtina": "",
    "Malisheva": "",
    "Drita": "",
    "Drenica Skënderaj": "",
    "Dukagjini": "",
    "Ballkani": "",
    "Ferizaj": "",

    # --- LATVIA ---
    "Grobiņa": "",
    "FS Jelgava": "",
    "FK Liepāja": "",
    "Riga FC": "",
    "FK Metta": "",
    "RFS": "",
    "SK Super Nova Salaspils": "",
    "BFC Daugavpils": "",
    "FK Tukums 2000/Telms": "",
    "FK Auda": "",

    # --- LITHUANIA ---
    "Panevėžys": "",
    "Šiauliai": "",
    "Banga": "",
    "Žalgiris": "",
    "Hegelmann Litauen": "",
    "Džiugas Telšiai": "",
    "Riteriai": "",
    "Dainava": "",
    "Sūduva": "",
    "Kauno Žalgiris": "",

    # --- MALTA ---
    "Valletta": "",
    "Birkirkara": "",
    "Floriana": "",
    "Naxxar Lions": "",
    "Marsaxlokk": "",
    "Zabbar St. Patrick": "",
    "Mosta": "",
    "Hamrun Spartans": "",
    "Tarxien Rainbows": "",
    "Gzira United": "",
    "Hibernians": "",
    "Sliema Wanderers": "",

    # --- MEXICO ---
    "Tigres UANL": "",
    "Juárez": "",
    "Toluca": "",
    "Cruz Azul": "",
    "Monterrey": "",
    "Club Tijuana": "",
    "Pachuca": "",
    "Guadalajara": "",
    "Pumas UNAM": "",
    "Mazatlán": "",
    "América": "",
    "Santos Laguna": "",
    "Necaxa": "",
    "Atlético de San Luis": "",
    "Atlas": "",
    "León": "",
    "Puebla": "",
    "Querétaro": "",

    # --- MOLDOVA ---
    "Dacia-Buiucani": "",
    "CSF Bălți": "",
    "Zimbru": "",
    "Sheriff": "",
    "Petrocub": "",
    "Politehnica UTM": "",
    "Spartanii Selemet": "",
    "Milsami": "",

    # --- NETHERLANDS ---
    "Heerenveen": "",
    "NEC": "",
    "Feyenoord": "",
    "Fortuna Sittard": "",
    "Groningen": "",
    "Go Ahead Eagles": "",
    "Telstar": "",
    "Twente": "",
    "PSV": "",
    "Sparta Rotterdam": "",
    "Volendam": "",
    "NAC Breda": "",
    "Heracles": "",
    "PEC Zwolle": "",
    "Utrecht": "",
    "Excelsior": "",
    "AZ": "",
    "Ajax": "",
    "TOP Oss": "",
    "Emmen": "",
    "Den Bosch": "",
    "VVV Venlo": "",
    "RKC Waalwijk": "",
    "Helmond Sport": "",
    "De Graafschap": "",
    "Roda JC": "",
    "Cambuur": "",
    "MVV": "",
    "Willem II": "",
    "AZ II": "",
    "Eindhoven": "",
    "Dordrecht": "",
    "Utrecht II": "",
    "ADO Den Haag": "",
    "Vitesse": "",
    "PSV II": "",
    "Ajax II": "",
    "Almere City": "",

    # --- NORTHERN IRELAND ---
    "Coleraine": "",
    "Crusaders": "",
    "Ballymena United": "",
    "Dungannon Swifts": "",
    "Bangor": "",
    "Portadown": "",
    "Carrick Rangers": "",
    "Larne": "",
    "Glenavon": "",
    "Glentoran": "",
    "Cliftonville": "",
    "Linfield": "",

    # --- NORWAY ---
    "Rosenborg": "",
    "Brann": "",
    "Sandefjord": "",
    "Tromsø": "",
    "Fredrikstad": "",
    "Bodø / Glimt": "",
    "Kristiansund": "",
    "Sarpsborg 08": "",
    "KFUM": "",
    "Viking": "",
    "Strømsgodset": "",
    "Bryne": "",
    "Molde": "",
    "HamKam": "",
    "Vålerenga": "",
    "Haugesund": "",
    "Moss": "",
    "Egersund": "",
    "Aalesund": "",
    "Kongsvinger": "",
    "Ranheim": "",
    "Start": "",
    "Lillestrøm": "",
    "Lyn": "",
    "Mjøndalen": "",
    "Raufoss": "",
    "Sogndal": "",
    "Hødd": "",
    "Stabæk": "",
    "Odds": "",
    "Åsane": "",
    "Skeid": "",
    "Grorud": "",
    "Brattvåg": "",




   
}

# Normalized lookup
_FM = {_norm(k): v.strip() for k, v in FOTMOB_TEAM_URLS.items() if str(v).strip()}

def get_fotmob_url(team: str) -> str:
    return _FM.get(_norm(team), "")

