# team_fotmob_urls.py
import unicodedata

def _norm(s: str) -> str:
    if s is None:
        return ""
    s = unicodedata.normalize("NFKD", str(s)).encode("ascii", "ignore").decode("ascii")
    return " ".join(s.strip().lower().split())

# =====================================================
# PASTE FOTMOB URLS ONLY
# Leave "" if you don't have it yet
# =====================================================

FOTMOB_TEAM_URLS = {

    # --- ENGLAND / UK ---
    "Liverpool": "https://www.fotmob.com/teams/8650/squad/liverpool",
    "Sunderland": "https://www.fotmob.com/teams/8472/squad/sunderland",
    "Arsenal": "https://www.fotmob.com/teams/9825/squad/arsenal",
    "Bournemouth": "https://www.fotmob.com/teams/8678/squad/afc-bournemouth",
    "Brighton": "https://www.fotmob.com/teams/10204/squad/brighton-hove-albion",
    "Fulham": "https://www.fotmob.com/teams/9879/squad/fulham",
    "West Ham United": "https://www.fotmob.com/teams/8654/squad/west-ham-united",
    "Brentford": "https://www.fotmob.com/teams/9937/squad/brentford",
    "Crystal Palace": "https://www.fotmob.com/teams/9826/squad/crystal-palace",
    "Burnley": "https://www.fotmob.com/teams/8191/squad/burnley",
    "Tottenham Hotspur": "https://www.fotmob.com/teams/8586/squad/tottenham-hotspur",
    "Nottingham Forest": "https://www.fotmob.com/teams/10203/squad/nottingham-forest",
    "Everton": "",
    "Aston Villa": "",
    "Manchester City": "",
    "Manchester United": "",
    "Newcastle United": "",
    "Chelsea": "",
    "Leeds United": "",
    "Wolverhampton Wanderers": "",
    "Derby County": "",
    "Coventry City": "",
    "Norwich City": "",
    "Swansea City": "https://www.fotmob.com/teams/10003/squad/swansea-city",
    "Middlesbrough": "",
    "Preston North End": "",
    "Millwall": "",
    "Stoke City": "https://www.fotmob.com/teams/10194/squad/stoke-city",
    "Hull City": "",
    "Charlton Athletic": "",
    "Wrexham": "",
    "Oxford United": "",
    "Ipswich Town": "",
    "Birmingham City": "",
    "Bristol City": "",
    "Sheffield United": "",
    "Sheffield Wednesday": "",
    "West Bromwich Albion": "",
    "Queens Park Rangers": "",
    "Leicester City": "",
    "Blackburn Rovers": "",
    "Portsmouth": "",
    "Southampton": "",
    "Watford": "",
    "Lincoln City": "",
    "Plymouth Argyle": "",
    "Bradford City": "",
    "Stockport County": "",
    "Exeter City": "",
    "Doncaster Rovers": "",
    "Rotherham United": "",
    "AFC Wimbledon": "",
    "Wigan Athletic": "",
    "Blackpool": "",
    "Reading": "",
    "Peterborough United": "",
    "Mansfield Town": "",
    "Burton Albion": "",
    "Wycombe Wanderers": "",
    "Bolton Wanderers": "",
    "Luton Town": "",
    "Stevenage": "",
    "Cardiff City": "",
    "Huddersfield Town": "",
    "Barnsley": "",
    "Northampton Town": "",
    "Leyton Orient": "",
    "Port Vale": "",
    "Crawley Town": "",
    "Chesterfield": "",
    "Cheltenham Town": "",
    "Colchester United": "",
    "Grimsby Town": "",
    "Swindon Town": "",
    "Oldham Athletic": "",
    "Tranmere Rovers": "",
    "Cambridge United": "",
    "Notts County": "",
    "Walsall": "",
    "Salford City": "",
    "Fleetwood Town": "",
    "Barnet": "",
    "Newport County": "",
    "Bromley": "",
    "Shrewsbury Town": "",
    "Barrow": "",
    "Milton Keynes Dons": "",
    "Crewe Alexandra": "",
    "Gillingham": "",
    "Harrogate Town": "",
    "Accrington Stanley": "",
    "Bristol Rovers": "",
    "Halifax Town": "",
    "Eastleigh": "",
    "Yeovil Town": "",
    "Woking": "",
    "Boston United": "",
    "Solihull Moors": "",
    "Forest Green Rovers": "",
    "Truro City": "",
    "York City": "",
    "Hartlepool United": "",
    "Wealdstone": "",
    "Tamworth": "",
    "Braintree Town": "",
    "Altrincham": "",
    "Gateshead": "",
    "Boreham Wood": "",
    "Carlisle United": "",
    "Sutton United": "",
    "Brackley Town": "",
    "Southend United": "",
    "Aldershot Town": "",
    "Rochdale": "",
    "Morecambe": "",
    "Scunthorpe United": "",

    # --- ALBANIA ---
    "Flamurtari Vlorë": "",
    "AF Elbasani": "",
    "Teuta Durrës": "",
    "Egnatia Rrogozhinë": "",
    "Vllaznia Shkodër": "",
    "Dinamo City": "",
    "Bylis Ballsh": "",
    "Tirana": "",
    "Vora": "",
    "Partizani Tirana": "",

    # --- ARGENTINA ---
    "Boca Juniors": "",
    "River Plate": "",
    "Racing Club": "",
    "Independiente": "",
    "San Lorenzo": "",
    "Lanús": "",
    "Rosario Central": "",
    "Huracán": "",
    "Estudiantes": "",
    "Vélez Sarsfield": "",
    "Banfield": "",
    "Defensa y Justicia": "",

    # --- ARMENIA ---
    "Pyunik": "",
    "Ararat": "",
    "Urartu": "",
    "Noah": "",
    "BKMA": "",

    # --- AUSTRALIA ---
    "Sydney": "",
    "Melbourne City": "",
    "Melbourne Victory": "",
    "Western Sydney Wanderers": "",
    "Brisbane Roar": "",
    "Adelaide United": "",
    "Central Coast Mariners": "",
    "Perth Glory": "",
    "Newcastle Jets": "",
    "Wellington Phoenix": "",
    "Macarthur": "",
    "Auckland FC": "",
}

# Normalized lookup
_FM = {_norm(k): v.strip() for k, v in FOTMOB_TEAM_URLS.items() if str(v).strip()}

def get_fotmob_url(team: str) -> str:
    return _FM.get(_norm(team), "")

