# team_fotmob_urls.py
import unicodedata

def _norm(s: str) -> str:
    if s is None:
        return ""
    s = unicodedata.normalize("NFKD", str(s)).encode("ascii", "ignore").decode("ascii")
    return " ".join(s.strip().lower().split())

# =====================================================
# PASTE FOTMOB URLS ONLY
# Leave "" if you don't have it yet
# =====================================================

FOTMOB_TEAM_URLS = {

    # --- ENGLAND / UK ---
    "Liverpool": "https://www.fotmob.com/teams/8650/squad/liverpool",
    "Sunderland": "https://www.fotmob.com/teams/8472/squad/sunderland",
    "Arsenal": "https://www.fotmob.com/teams/9825/squad/arsenal",
    "Bournemouth": "https://www.fotmob.com/teams/8678/squad/afc-bournemouth",
    "Brighton": "https://www.fotmob.com/teams/10204/squad/brighton-hove-albion",
    "Fulham": "https://www.fotmob.com/teams/9879/squad/fulham",
    "West Ham United": "https://www.fotmob.com/teams/8654/squad/west-ham-united",
    "Brentford": "https://www.fotmob.com/teams/9937/squad/brentford",
    "Crystal Palace": "https://www.fotmob.com/teams/9826/squad/crystal-palace",
    "Burnley": "https://www.fotmob.com/teams/8191/squad/burnley",
    "Tottenham Hotspur": "https://www.fotmob.com/teams/8586/squad/tottenham-hotspur",
    "Nottingham Forest": "https://www.fotmob.com/teams/10203/squad/nottingham-forest",
    "Everton": "https://www.fotmob.com/teams/8668/squad/everton",
    "Aston Villa": "https://www.fotmob.com/teams/10252/squad/aston-villa",
    "Manchester City": "https://www.fotmob.com/teams/8456/squad/manchester-city",
    "Manchester United": "https://www.fotmob.com/teams/10260/squad/manchester-united",
    "Newcastle United": "https://www.fotmob.com/teams/10261/squad/newcastle-united",
    "Chelsea": "https://www.fotmob.com/teams/8455/squad/chelsea",
    "Leeds United": "https://www.fotmob.com/teams/8463/squad/leeds-united",
    "Wolverhampton Wanderers": "https://www.fotmob.com/teams/8602/squad/wolverhampton-wanderers",
    "Derby County": "https://www.fotmob.com/teams/10170/squad/derby-county",
    "Coventry City": "https://www.fotmob.com/teams/8669/squad/coventry-city",
    "Norwich City": "https://www.fotmob.com/teams/9850/squad/norwich-city",
    "Swansea City": "https://www.fotmob.com/teams/10003/squad/swansea-city",
    "Middlesbrough": "https://www.fotmob.com/teams/8549/squad/middlesbrough",
    "Preston North End": "https://www.fotmob.com/teams/8411/squad/preston-north-end",
    "Millwall": "https://www.fotmob.com/teams/10004/squad/millwall",
    "Stoke City": "https://www.fotmob.com/teams/10194/squad/stoke-city",
    "Hull City": "",
    "Charlton Athletic": "https://www.fotmob.com/teams/8451/squad/charlton-athletic",
    "Wrexham": "https://www.fotmob.com/teams/9841/squad/wrexham",
    "Oxford United": "https://www.fotmob.com/teams/8653/squad/oxford-united",
    "Ipswich Town": "https://www.fotmob.com/teams/9902/squad/ipswich-town",
    "Birmingham City": "https://www.fotmob.com/teams/8658/squad/birmingham-city",
    "Bristol City": "https://www.fotmob.com/teams/8427/squad/bristol-city",
    "Sheffield United": "https://www.fotmob.com/teams/8657/squad/sheffield-united",
    "Sheffield Wednesday": "https://www.fotmob.com/teams/10163/squad/sheffield-wednesday",
    "West Bromwich Albion": "https://www.fotmob.com/teams/8659/squad/west-bromwich-albion",
    "Queens Park Rangers": "https://www.fotmob.com/teams/10172/squad/queens-park-rangers",
    "Leicester City": "https://www.fotmob.com/teams/8197/squad/leicester-city",
    "Blackburn Rovers": "https://www.fotmob.com/teams/8655/squad/blackburn-rovers",
    "Portsmouth": "https://www.fotmob.com/teams/8462/squad/portsmouth",
    "Southampton": "https://www.fotmob.com/teams/8466/squad/southampton",
    "Watford": "https://www.fotmob.com/teams/9817/squad/watford",
    "Lincoln City": "https://www.fotmob.com/teams/8430/squad/lincoln-city",
    "Plymouth Argyle": "https://www.fotmob.com/teams/8401/squad/plymouth-argyle",
    "Bradford City": "https://www.fotmob.com/teams/8484/squad/bradford-city",
    "Stockport County": "https://www.fotmob.com/teams/10007/squad/stockport-county",
    "Exeter City": "https://www.fotmob.com/teams/9833/squad/exeter-city",
    "Doncaster Rovers": "https://www.fotmob.com/teams/9903/squad/doncaster-rovers",
    "Rotherham United": "https://www.fotmob.com/teams/8119/squad/rotherham-united",
    "AFC Wimbledon": "https://www.fotmob.com/teams/158319/squad/afc-wimbledon",
    "Wigan Athletic": "https://www.fotmob.com/teams/8528/squad/wigan-athletic",
    "Blackpool": "https://www.fotmob.com/teams/8483/squad/blackpool",
    "Reading": "https://www.fotmob.com/teams/9798/squad/reading",
    "Peterborough United": "https://www.fotmob.com/teams/8677/squad/peterborough-united",
    "Mansfield Town": "https://www.fotmob.com/teams/9818/squad/mansfield-town",
    "Burton Albion": "https://www.fotmob.com/teams/9792/squad/burton-albion",
    "Wycombe Wanderers": "https://www.fotmob.com/teams/8676/squad/wycombe-wanderers",
    "Bolton Wanderers": "https://www.fotmob.com/teams/8559/squad/bolton-wanderers",
    "Luton Town": "https://www.fotmob.com/teams/8346/squad/luton-town",
    "Stevenage": "https://www.fotmob.com/teams/10253/squad/stevenage",
    "Cardiff City": "https://www.fotmob.com/teams/8344/squad/cardiff-city",
    "Huddersfield Town": "https://www.fotmob.com/teams/9796/squad/huddersfield-town",
    "Barnsley": "https://www.fotmob.com/teams/8283/squad/barnsley",
    "Northampton Town": "https://www.fotmob.com/teams/8651/squad/northampton-town",
    "Leyton Orient": "https://www.fotmob.com/teams/8351/squad/leyton-orient",
    "Port Vale": "https://www.fotmob.com/teams/9799/squad/port-vale",
    "Crawley Town": "https://www.fotmob.com/teams/8647/squad/crawley-town",
    "Chesterfield": "https://www.fotmob.com/teams/9786/squad/chesterfield",
    "Cheltenham Town": "https://www.fotmob.com/teams/8680/squad/cheltenham-town",
    "Colchester United": "https://www.fotmob.com/teams/8416/squad/colchester-united",
    "Grimsby Town": "https://www.fotmob.com/teams/10005/squad/grimsby-town",
    "Swindon Town": "https://www.fotmob.com/teams/9795/squad/swindon-town",
    "Oldham Athletic": "https://www.fotmob.com/teams/9785/squad/oldham-athletic",
    "Tranmere Rovers": "https://www.fotmob.com/teams/8313/squad/tranmere-rovers",
    "Cambridge United": "https://www.fotmob.com/teams/9834/squad/cambridge-united",
    "Notts County": "https://www.fotmob.com/teams/9819/squad/notts-county",
    "Walsall": "https://www.fotmob.com/teams/10006/squad/walsall",
    "Salford City": "https://www.fotmob.com/teams/282326/squad/salford-city",
    "Fleetwood Town": "https://www.fotmob.com/teams/45723/squad/fleetwood-town",
    "Barnet": "https://www.fotmob.com/teams/8175/squad/barnet",
    "Newport County": "https://www.fotmob.com/teams/10262/squad/newport-county",
    "Bromley": "https://www.fotmob.com/teams/45729/squad/bromley",
    "Shrewsbury Town": "https://www.fotmob.com/teams/9896/squad/shrewsbury-town",
    "Barrow": "https://www.fotmob.com/teams/6350/squad/barrow",
    "Milton Keynes Dons": "https://www.fotmob.com/teams/8645/squad/milton-keynes-dons",
    "Crewe Alexandra": "https://www.fotmob.com/teams/9784/squad/crewe-alexandra",
    "Gillingham": "https://www.fotmob.com/teams/10173/squad/gillingham",
    "Harrogate Town": "https://www.fotmob.com/teams/7946/squad/harrogate-town",
    "Accrington Stanley": "https://www.fotmob.com/teams/8671/squad/accrington-stanley",
    "Bristol Rovers": "https://www.fotmob.com/teams/10104/squad/bristol-rovers",
    "Halifax Town": "https://www.fotmob.com/teams/10195/squad/fc-halifax-town",
    "Eastleigh": "https://www.fotmob.com/teams/161803/squad/eastleigh",
    "Yeovil Town": "https://www.fotmob.com/teams/10198/squad/yeovil-town",
    "Woking": "https://www.fotmob.com/teams/8345/squad/woking",
    "Boston United": "https://www.fotmob.com/teams/8646/squad/boston-united",
    "Solihull Moors": "https://www.fotmob.com/teams/161801/squad/solihull-moors",
    "Forest Green Rovers": "https://www.fotmob.com/teams/9828/squad/forest-green-rovers",
    "Truro City": "https://www.fotmob.com/teams/177067/squad/truro-city",
    "York City": "https://www.fotmob.com/teams/9916/squad/york-city",
    "Hartlepool United": "https://www.fotmob.com/teams/8488/squad/hartlepool-united",
    "Wealdstone": "https://www.fotmob.com/teams/161812/squad/wealdstone",
    "Tamworth": "https://www.fotmob.com/teams/10254/squad/tamworth",
    "Braintree Town": "https://www.fotmob.com/teams/5763/squad/braintree-town",
    "Altrincham": "https://www.fotmob.com/teams/9915/squad/altrincham",
    "Gateshead": "https://www.fotmob.com/teams/6189/squad/gateshead-fc",
    "Boreham Wood": "https://www.fotmob.com/teams/2488/squad/boreham-wood",
    "Carlisle United": "https://www.fotmob.com/teams/10196/squad/carlisle-united",
    "Sutton United": "https://www.fotmob.com/teams/158316/squad/sutton-united",
    "Brackley Town": "https://www.fotmob.com/teams/158321/squad/brackley-town",
    "Southend United": "https://www.fotmob.com/teams/8652/squad/southend-united",
    "Aldershot Town": "https://www.fotmob.com/teams/8465/squad/aldershot-town",
    "Rochdale": "https://www.fotmob.com/teams/8493/squad/rochdale",
    "Morecambe": "https://www.fotmob.com/teams/8489/squad/morecambe",
    "Scunthorpe United": "https://www.fotmob.com/teams/8412/squad/scunthorpe-united",

    # --- ALBANIA ---
    "Flamurtari Vlorë": "https://www.fotmob.com/teams/8041/overview/fk-vardar-skopje",
    "AF Elbasani": "https://www.fotmob.com/teams/10038/overview/elbasani",
    "Teuta Durrës": "https://www.fotmob.com/teams/10037/overview/teuta-durres",
    "Egnatia Rrogozhinë": "https://www.fotmob.com/teams/10039/overview/egnatia",
    "Vllaznia Shkodër": "https://www.fotmob.com/teams/10034/overview/vllaznia",
    "Dinamo City": "https://www.fotmob.com/teams/10027/overview/fc-dinamo-city",
    "Bylis Ballsh": "https://www.fotmob.com/teams/10026/overview/bylis",
    "Tirana": "https://www.fotmob.com/teams/10029/overview/kf-tirana",
    "Vora": "https://www.fotmob.com/teams/585403/overview/vora",
    "Partizani Tirana": "https://www.fotmob.com/teams/10028/overview/partizani",

    # --- ARGENTINA ---
    "Boca Juniors": "https://www.fotmob.com/teams/10077/squad/boca-juniors",
    "River Plate": "https://www.fotmob.com/teams/10076/squad/river-plate",
    "Racing Club": "https://www.fotmob.com/teams/10080/squad/racing-club",
    "Independiente": "https://www.fotmob.com/teams/10078/squad/independiente",
    "San Lorenzo": "https://www.fotmob.com/teams/10083/squad/san-lorenzo",
    "Lanús": "https://www.fotmob.com/teams/10082/squad/lanus",
    "Rosario Central": "https://www.fotmob.com/teams/10084/squad/rosario-central",
    "Huracán": "https://www.fotmob.com/teams/10081/squad/huracan",
    "Estudiantes": "https://www.fotmob.com/teams/10094/squad/estudiantes",
    "Vélez Sarsfield": "https://www.fotmob.com/teams/10079/squad/velez-sarsfield",
    "Banfield": "https://www.fotmob.com/teams/10087/squad/banfield",
    "Defensa y Justicia": "https://www.fotmob.com/teams/161730/squad/defensa-y-justicia",

    # --- ARMENIA ---
    "Pyunik": "https://www.fotmob.com/teams/6345/overview/pyunik",
    "Ararat": "https://www.fotmob.com/teams/866109/overview/ararat-armenia",
    "Urartu": "https://www.fotmob.com/teams/7979/overview/urartu-fc",
    "Noah": "https://www.fotmob.com/teams/866111/squad/fc-noah",
    "BKMA": "https://www.fotmob.com/teams/1078402/overview/bkma",

    # --- AUSTRALIA ---
    "Sydney": "https://www.fotmob.com/teams/10164/squad/sydney-fc",
    "Melbourne City": "https://www.fotmob.com/teams/203576/squad/melbourne-city-fc",
    "Melbourne Victory": "https://www.fotmob.com/teams/6230/overview/melbourne-victory",
    "Western Sydney Wanderers": "https://www.fotmob.com/teams/323834/squad/western-sydney-wanderers-fc",
    "Brisbane Roar": "https://www.fotmob.com/teams/8118/squad/brisbane-roar-fc",
    "Adelaide United": "https://www.fotmob.com/teams/8008/squad/adelaide-united",
    "Central Coast Mariners": "https://www.fotmob.com/teams/8164/squad/central-coast-mariners",
    "Perth Glory": "https://www.fotmob.com/teams/7961/squad/perth-glory",
    "Newcastle Jets": "https://www.fotmob.com/teams/6454/squad/newcastle-jets",
    "Wellington Phoenix": "https://www.fotmob.com/teams/78785/squad/wellington-phoenix",
    "Macarthur": "https://www.fotmob.com/teams/1209973/squad/macarthur-fc",
    "Auckland FC": "https://www.fotmob.com/teams/1642068/squad/auckland-fc",

    # --- AUSTRIA ---
    "Grazer AK": "https://www.fotmob.com/teams/10012/squad/grazer-ak",
    "LASK": "https://www.fotmob.com/teams/9977/squad/lask",
    "Austria Wien": "https://www.fotmob.com/teams/10011/squad/austria-wien",
    "Rheindorf Altach": "https://www.fotmob.com/teams/10008/squad/altach",
    "Blau-Weiß Linz": "https://www.fotmob.com/teams/2433/squad/bw-linz",
    "Ried": "https://www.fotmob.com/teams/10017/squad/ried",
    "WSG Swarovski Tirol": "https://www.fotmob.com/teams/1583/squad/wsg-tirol",
    "Hartberg": "https://www.fotmob.com/teams/10056/squad/hartberg",
    "Sturm Graz": "https://www.fotmob.com/teams/10014/squad/sturm-graz",
    "Salzburg": "https://www.fotmob.com/teams/10013/squad/salzburg",
    "Rapid Wien": "https://www.fotmob.com/teams/10015/squad/rapid-wien",
    "Wolfsberger AC": "https://www.fotmob.com/teams/1954/squad/wolfsberger-ac",
    "Austria Lustenau": "https://www.fotmob.com/teams/9982/squad/austria-lustenau",
    "St. Pölten": "https://www.fotmob.com/teams/1907/squad/skn-st-polten",
    "Bregenz": "https://www.fotmob.com/teams/80619/squad/sw-bregenz",
    "Rapid Wien II": "https://www.fotmob.com/teams/1952/squad/rapid-wien-ii",
    "Austria Salzburg": "https://www.fotmob.com/teams/206091/squad/austria-salzburg",
    "Floridsdorfer AC": "https://www.fotmob.com/teams/8274/squad/floridsdorfer-ac",
    "Kapfenberger SV": "https://www.fotmob.com/teams/9979/squad/kapfenberger-sv",
    "Austria Wien II": "https://www.fotmob.com/teams/10248/squad/austria-wien-ii",
    "Liefering": "https://www.fotmob.com/teams/1915/squad/fc-liefering",
    "Austria Klagenfurt": "https://www.fotmob.com/teams/10009/squad/sk-austria-klagenfurt",
    "Amstetten": "https://www.fotmob.com/teams/8326/squad/amstetten",
    "WSPG Wels": "https://www.fotmob.com/teams/946908/squad/spg-hogo-wels",
    "Admira": "https://www.fotmob.com/teams/10053/squad/admira-wacker",
    "Sturm Graz II": "https://www.fotmob.com/teams/1921/squad/sturm-graz-ii",
    "First Vienna": "https://www.fotmob.com/teams/2030/squad/first-vienna-fc",
    "Stripfing": "https://www.fotmob.com/teams/611179/overview/sv-stripfing",

    # --- AZERBAIJAN ---
    "Sabah": "https://www.fotmob.com/teams/951893/overview/sabah-fk",
    "Neftchi": "https://www.fotmob.com/teams/4617/overview/fk-neftchi",
    "Zira": "https://www.fotmob.com/teams/577619/overview/zira",
    "Shamakhi FK": "https://www.fotmob.com/teams/2103/overview/shamakhi-fk",
    "Karvan": "https://www.fotmob.com/teams/8045/overview/karvan-fk",
    "İmişli": "https://www.fotmob.com/teams/1786024/overview/imisli-fk",
    "Turan-T": "https://www.fotmob.com/teams/4674/overview/turan-tovuz",
    "Qabala": "https://www.fotmob.com/teams/8076/overview/fk-qabala",
    "Araz": "https://www.fotmob.com/teams/485832/overview/araz-pfk",
    "Kapaz": "https://www.fotmob.com/teams/4150/overview/fc-kapaz",
    "Sumqayıt": "https://www.fotmob.com/teams/213987/overview/sumqayit",
    "Qarabag": "https://www.fotmob.com/teams/7981/overview/qarabag-fk",

    # --- BELGIUM ---
    "Club Brugge": "https://www.fotmob.com/teams/8342/squad/club-brugge",
    "Sint-Truiden": "https://www.fotmob.com/teams/9997/squad/sttruiden",
    "Genk": "https://www.fotmob.com/teams/9987/squad/genk",
    "La Louvière": "https://www.fotmob.com/teams/1218969/squad/raal-la-louviere",
    "Zulte-Waregem": "https://www.fotmob.com/teams/10000/squad/zulte-waregem",
    "Antwerp": "https://www.fotmob.com/teams/9988/squad/royal-antwerp",
    "Westerlo": "https://www.fotmob.com/teams/10001/squad/westerlo",
    "OH Leuven": "https://www.fotmob.com/teams/1773/squad/oh-leuven",
    "Anderlecht": "https://www.fotmob.com/teams/8635/squad/anderlecht",
    "Gent": "https://www.fotmob.com/teams/9991/squad/gent",
    "Dender": "https://www.fotmob.com/teams/7947/squad/fcv-dender-eh",
    "Cercle Brugge": "https://www.fotmob.com/teams/9984/squad/cercle-brugge",
    "Mechelen": "https://www.fotmob.com/teams/8203/squad/kv-mechelen",
    "Charleroi": "https://www.fotmob.com/teams/9986/squad/sporting-charleroi",
    "Standard Liège": "https://www.fotmob.com/teams/9985/squad/standard-liege",
    "Union Saint-Gilloise": "https://www.fotmob.com/teams/7978/squad/union-stgilloise",
    "Patro Eisden": "https://www.fotmob.com/teams/274583/overview/patro-eisden",
    "Beerschot VA": "https://www.fotmob.com/teams/583877/overview/beerschot",
    "Francs Borains": "https://www.fotmob.com/teams/96953/overview/francs-borains",
    "Kortrijk": "https://www.fotmob.com/teams/8571/overview/kortrijk",
    "Lommel SK": "https://www.fotmob.com/teams/6702/overview/lommel",
    "Lokeren-Temse": "https://www.fotmob.com/teams/213307/overview/ksc-lokeren",
    "Lierse Kempenzonen": "https://www.fotmob.com/teams/465631/overview/k-lierse-sk",
    "Liège": "https://www.fotmob.com/teams/6363/overview/fc-liege",
    "Eupen": "https://www.fotmob.com/teams/6351/overview/eupen",
    "Club Brugge II": "https://www.fotmob.com/teams/1173026/overview/club-brugge-nxt",
    "RFC Seraing": "https://www.fotmob.com/teams/149408/overview/rfc-seraing",
    "SK Beveren": "https://www.fotmob.com/teams/8475/overview/sk-beveren",
    "Gent II": "https://www.fotmob.com/teams/1379188/overview/gent-u23",
    "Olympic Charleroi": "https://www.fotmob.com/teams/4137/overview/olympic-de-charleroi",
    "Genk II": "https://www.fotmob.com/teams/1378463/overview/genk-u23",
    "Anderlecht II": "https://www.fotmob.com/teams/1378461/overview/anderlecht-futures",
    "RWD Molenbeek": "https://www.fotmob.com/teams/9992/overview/rwdm-brussels",

    # --- BOLIVIA ---
    "Guabirá": "https://www.fotmob.com/teams/114830/squad/guabira",
    "Real Tomayapo": "https://www.fotmob.com/teams/1074622/squad/real-tomayapo",
    "Always Ready": "https://www.fotmob.com/teams/805913/squad/always-ready",
    "Real Oruro": "https://www.fotmob.com/teams/1504766/squad/cdt-real-oruro",
    "Universitario de Vinto": "https://www.fotmob.com/teams/879029/squad/universitario-de-vinto",
    "The Strongest": "https://www.fotmob.com/teams/2527/squad/strongest",
    "Wilstermann": "https://www.fotmob.com/teams/1892/squad/jorge-wilstermann",
    "Gualberto Villarroel SJ": "https://www.fotmob.com/teams/1504770/squad/gv-san-jose",
    "Aurora": "https://www.fotmob.com/teams/49720/squad/aurora",
    "Blooming": "https://www.fotmob.com/teams/49678/squad/blooming",
    "Independiente Petrolero": "https://www.fotmob.com/teams/958325/squad/independiente-petrolero",
    "San Antonio Bulo Bulo": "https://www.fotmob.com/teams/1297060/squad/san-antonio-bulo-bulo",
    "Nacional Potosí": "https://www.fotmob.com/teams/164353/squad/nacional-potosi",
    "Bolívar": "https://www.fotmob.com/teams/5983/squad/bolivar",
    "ABB": "https://www.fotmob.com/teams/1297346/squad/abb",
    "Oriente Petrolero": "https://www.fotmob.com/teams/1844/squad/oriente-petrolero",

    # --- BOSNIA ---
    "Željezničar": "https://www.fotmob.com/teams/10108/overview/zeljeznicar",
    "Široki Brijeg": "https://www.fotmob.com/teams/10112/overview/siroki-brijeg",
    "Sloga Doboj": "https://www.fotmob.com/teams/187928/overview/sloga-doboj",
    "Posušje": "https://www.fotmob.com/teams/10111/overview/posusje",
    "Sarajevo": "https://www.fotmob.com/teams/10105/overview/fk-sarajevo",
    "Borac Banja Luka": "https://www.fotmob.com/teams/10116/overview/borac-banja-luka",
    "Rudar Prijedor": "https://www.fotmob.com/teams/175797/overview/rudar-prijedor",
    "Radnik Bijeljina": "https://www.fotmob.com/teams/10124/overview/radnik-bijeljina",
    "Velež": "https://www.fotmob.com/teams/10122/overview/fk-velez-mostar",
    "Zrinjski": "https://www.fotmob.com/teams/10107/squad/zrinjski-mostar",

    # --- BRAZIL ---
    "Fluminense": "https://www.fotmob.com/teams/9863/squad/fluminense",
    "Santos": "https://www.fotmob.com/teams/8514/squad/santos-fc",
    "Mirassol": "https://www.fotmob.com/teams/163782/squad/mirassol",
    "Flamengo": "https://www.fotmob.com/teams/9770/squad/flamengo",
    "Atlético Mineiro": "https://www.fotmob.com/teams/10272/squad/atletico-mg",
    "Ceará": "https://www.fotmob.com/teams/172341/squad/ceara",
    "Vasco da Gama": "https://www.fotmob.com/teams/10276/squad/vasco-da-gama",
    "São Paulo": "https://www.fotmob.com/teams/10277/squad/sao-paulo",
    "Cruzeiro": "https://www.fotmob.com/teams/9781/squad/cruzeiro",
    "Red Bull Bragantino": "https://www.fotmob.com/teams/109705/squad/red-bull-bragantino",
    "Bahia": "https://www.fotmob.com/teams/7877/squad/bahia",
    "Grêmio": "https://www.fotmob.com/teams/9769/squad/gremio",
    "Vitória": "https://www.fotmob.com/teams/7733/squad/vitoria",
    "Botafogo": "https://www.fotmob.com/teams/8517/squad/botafogo-rj",
    "Juventude": "https://www.fotmob.com/teams/10274/overview/juventude",
    "Internacional": "https://www.fotmob.com/teams/8702/squad/internacional",
    "Sport Recife": "https://www.fotmob.com/teams/6305/squad/sport-recife",
    "Corinthians": "https://www.fotmob.com/teams/9808/squad/corinthians",
    "Fortaleza": "https://www.fotmob.com/teams/8287/squad/fortaleza",
    "Palmeiras": "https://www.fotmob.com/teams/10283/squad/palmeiras",
    "Ferroviária": "https://www.fotmob.com/teams/581832/squad/ferroviaria",
    "Chapecoense": "https://www.fotmob.com/teams/197693/squad/chapecoense-af",
    "Goiás": "https://www.fotmob.com/teams/9862/overview/goias",
    "América Mineiro": "https://www.fotmob.com/teams/1757/overview/america-mg",
    "Avaí": "https://www.fotmob.com/teams/104822/squad/avai-fc",
    "Remo": "https://www.fotmob.com/teams/1626/squad/remo",
    "Criciúma": "https://www.fotmob.com/teams/7729/squad/criciuma",
    "CRB": "https://www.fotmob.com/teams/104821/squad/crb",
    "Botafogo SP": "https://www.fotmob.com/teams/8355/squad/botafogo-sp",
    "Athletic Club": "https://www.fotmob.com/teams/1221604/overview/athletic-club",
    "Vila Nova": "https://www.fotmob.com/teams/109706/overview/vila-nova",
    "Operário PR": "https://www.fotmob.com/teams/197429/squad/operario-ferroviario",
    "Grêmio Novorizontino": "https://www.fotmob.com/teams/581838/squad/novorizontino",
    "Coritiba": "https://www.fotmob.com/teams/9767/squad/coritiba",
    "Amazonas": "https://www.fotmob.com/teams/1340094/squad/amazonas-fc",
    "Cuiabá": "https://www.fotmob.com/teams/197815/squad/cuiaba",
    "Athletico Paranaense": "https://www.fotmob.com/teams/10273/squad/athletico-paranaense",
    "Atlético GO": "https://www.fotmob.com/teams/165545/overview/atletico-go",
    "Paysandu": "https://www.fotmob.com/teams/6546/squad/paysandu",
    "Volta Redonda": "https://www.fotmob.com/teams/198135/squad/volta-redonda",

    # --- BULGARIA ---
    "Spartak Varna": "https://www.fotmob.com/teams/10145/squad/spartak-varna",
    "Levski Sofia": "https://www.fotmob.com/teams/8632/squad/levski-sofia",
    "Dobrudzha 1919": "https://www.fotmob.com/teams/10140/squad/dobrudzha-dobrich",
    "Slavia Sofia": "https://www.fotmob.com/teams/10134/squad/slavia-sofia",
    "Arda": "https://www.fotmob.com/teams/944173/squad/arda-kardzhali",
    "Botev Vratsa": "https://www.fotmob.com/teams/187880/squad/botev-vratsa",
    "Septemvri Sofia": "https://www.fotmob.com/teams/312976/squad/septemvri-sofia",
    "CSKA Sofia": "https://www.fotmob.com/teams/10144/squad/cska-sofia",
    "Montana": "https://www.fotmob.com/teams/46475/squad/montana",
    "Botev Plovdiv": "https://www.fotmob.com/teams/10131/squad/botev-plovdiv",
    "Cherno More": "https://www.fotmob.com/teams/10141/squad/cherno-more-varna",
    "Beroe": "https://www.fotmob.com/teams/10126/squad/beroe",
    "Lokomotiv Plovdiv": "https://www.fotmob.com/teams/10129/squad/lokomotiv-plovdiv",
    "Lokomotiv Sofia 1929": "https://www.fotmob.com/teams/10128/squad/pfc-lokomotiv-sofia-1929",
    "Ludogorets": "https://www.fotmob.com/teams/210173/squad/ludogorets-razgrad",
    "CSKA 1948 Sofia": "https://www.fotmob.com/teams/10144/squad/cska-sofia",

    # --- CHILE ---
    "Universidad Católica": "https://www.fotmob.com/teams/6458/squad/universidad-catolica",
    "Audax Italiano": "https://www.fotmob.com/teams/4058/squad/audax-italiano",
    "Ñublense": "https://www.fotmob.com/teams/49559/squad/nublense",
    "Unión La Calera": "https://www.fotmob.com/teams/192435/squad/union-la-calera",
    "Coquimbo Unido": "https://www.fotmob.com/teams/4062/squad/coquimbo-unido",
    "Huachipato": "https://www.fotmob.com/teams/4056/squad/huachipato",
    "O'Higgins": "https://www.fotmob.com/teams/6296/squad/ohiggins",
    "Palestino": "https://www.fotmob.com/teams/6455/squad/palestino",
    "Cobresal": "https://www.fotmob.com/teams/4055/squad/cobresal",
    "Deportes Iquique": "https://www.fotmob.com/teams/162904/squad/deportes-iquique",
    "La Serena": "https://www.fotmob.com/teams/1891/squad/la-serena",
    "Colo Colo": "https://www.fotmob.com/teams/7815/squad/colo-colo",
    "Deportes Limache": "https://www.fotmob.com/teams/584840/squad/deportes-limache",
    "Universidad de Chile": "https://www.fotmob.com/teams/6310/squad/universidad-de-chile",
    "Unión Española": "https://www.fotmob.com/teams/7843/squad/union-espanola",

    # --- CHINA ---
    "Zhejiang Professional": "https://www.fotmob.com/teams/51443/squad/zhejiang-professional",
    "Tianjin Tigers": "https://www.fotmob.com/teams/4189/squad/tianjin-jinmen-tiger",
    "Meizhou Hakka": "https://www.fotmob.com/teams/585808/squad/meizhou-hakka",
    "Shanghai Shenhua": "https://www.fotmob.com/teams/6628/squad/shanghai-shenhua",
    "Qingdao West Coast": "https://www.fotmob.com/teams/1283248/squad/qingdao-west-coast",
    "Chengdu Rongcheng": "https://www.fotmob.com/teams/737052/squad/chengdu-rongcheng-fc",
    "Yunnan Yukun": "https://www.fotmob.com/teams/1477056/squad/yunnan-yukun",
    "Beijing Guoan": "https://www.fotmob.com/teams/4177/squad/beijing-guoan",
    "Henan": "https://www.fotmob.com/teams/51442/squad/henan-fc",
    "Shanghai Port": "https://www.fotmob.com/teams/198616/squad/shanghai-port",
    "Qingdao Hainiu": "https://www.fotmob.com/teams/4183/squad/qingdao-hainiu",
    "Dalian Young Boy": "https://www.fotmob.com/teams/1477043/squad/dalian-yingbo",
    "Shandong Taishan": "https://www.fotmob.com/teams/8623/squad/shandong-taishan",
    "Changchun Yatai": "https://www.fotmob.com/teams/6401/squad/changchun-yatai",
    "Shenzhen Peng City": "https://www.fotmob.com/teams/930027/squad/shenzhen-peng-city",
    "Wuhan Three Towns": "https://www.fotmob.com/teams/1029687/squad/wuhan-three-towns",

    # --- COLOMBIA ---
    "Medellín": "https://www.fotmob.com/teams/2528/overview/independiente-medellin",
    "Santa Fe": "https://www.fotmob.com/teams/7818/overview/santa-fe",
    "Junior": "https://www.fotmob.com/teams/2254/overview/junior-fc",
    "Atlético Bucaramanga": "https://www.fotmob.com/teams/4401/overview/bucaramanga",
    "Atlético Nacional": "https://www.fotmob.com/teams/6368/overview/atletico-nacional",
    "Tolima": "https://www.fotmob.com/teams/1894/overview/tolima",
    "América de Cali": "https://www.fotmob.com/teams/10280/overview/america-de-cali",
    "Deportivo Cali": "https://www.fotmob.com/teams/6387/overview/deportivo-cali",
    "Águilas Doradas": "https://www.fotmob.com/teams/193025/overview/aguilas-doradas",
    "Once Caldas": "https://www.fotmob.com/teams/6024/overview/once-caldas",
    "Llaneros": "https://www.fotmob.com/teams/348397/overview/llaneros-fc",
    "La Equidad": "https://www.fotmob.com/teams/47240/overview/internacional-de-bogota",
    "Deportivo Pasto": "https://www.fotmob.com/teams/4405/overview/deportivo-pasto",
    "Millonarios": "https://www.fotmob.com/teams/4403/overview/millonarios",
    "Deportivo Pereira": "https://www.fotmob.com/teams/4404/overview/deportivo-pereira",
    "Unión Magdalena": "https://www.fotmob.com/teams/4408/overview/union-magdalena",
    "Alianza": "https://www.fotmob.com/teams/193029/overview/alianza-fc",
    "Boyacá Chicó": "https://www.fotmob.com/teams/6255/overview/chico-fc",
    "Envigado": "https://www.fotmob.com/teams/4402/overview/envigado",

    # --- CROATIA ---
    "Slaven Belupo": https://www.fotmob.com/teams/1581/squad/slaven"",
    "Gorica": "https://www.fotmob.com/teams/206560/squad/hnk-gorica",
    "Osijek": "https://www.fotmob.com/teams/10157/squad/osijek",
    "Vukovar": "https://www.fotmob.com/teams/45228/squad/vukovar-91",
    "Istra 1961": "https://www.fotmob.com/teams/6038/squad/nk-istra-1961",
    "Dinamo Zagreb": "https://www.fotmob.com/teams/10156/squad/dinamo-zagreb",
    "Rijeka": "https://www.fotmob.com/teams/10162/squad/rijeka",
    "Varaždin": "https://www.fotmob.com/teams/10165/squad/nk-varazdin",
    "Lokomotiva Zagreb": "https://www.fotmob.com/teams/175388/squad/nk-lokomotiva",
    "Hajduk Split": "https://www.fotmob.com/teams/10154/squad/hajduk-split",

    # --- CYPRUS ---
    "Apollon": "https://www.fotmob.com/teams/8003/squad/apollon-limassol",
    "Akritas": "https://www.fotmob.com/teams/184615/squad/akritas-chlorakas",
    "Omonia Aradippou": "https://www.fotmob.com/teams/8044/squad/omonia-nicosia",
    "Ethnikos Achnas": "https://www.fotmob.com/teams/8334/squad/ethnikos-achnas",
    "APOEL": "https://www.fotmob.com/teams/8621/squad/apoel-nicosia",
    "Anorthosis": "https://www.fotmob.com/teams/6243/squad/anorthosis",
    "AEK Larnaca": "https://www.fotmob.com/teams/7797/squad/aek-larnaca",
    "Ypsonas": "https://www.fotmob.com/teams/1075325/squad/krasava-ypsonas-fc",
    "Enosis": "https://www.fotmob.com/teams/4126/squad/enosis-paralimni",
    "Aris": "https://www.fotmob.com/teams/2136/squad/aris-limassol",
    "Omonia Nicosia": "https://www.fotmob.com/teams/8044/squad/omonia-nicosia",
    "Pafos": "https://www.fotmob.com/teams/2137/squad/pafos-fc",
    "AEL": "https://www.fotmob.com/teams/2134/overview/ael-limassol",

    # --- CZECH REPUBLIC ---
    "Jablonec": "https://www.fotmob.com/teams/7758/squad/jablonec",
    "Sparta Praha": "https://www.fotmob.com/teams/10247/squad/sparta-prague",
    "Bohemians 1905": "https://www.fotmob.com/teams/1670/squad/bohemians-1905",
    "Teplice": "https://www.fotmob.com/teams/4721/squad/teplice",
    "Zlín": "https://www.fotmob.com/teams/1860/squad/fc-zlin",
    "Slovan Liberec": "https://www.fotmob.com/teams/10245/overview/slovan-liberec",
    "Hradec Králové": "https://www.fotmob.com/teams/1712/squad/hradec-kralove",
    "Sigma Olomouc": "https://www.fotmob.com/teams/6461/squad/sigma-olomouc",
    "Viktoria Plzeň": "https://www.fotmob.com/teams/6033/squad/viktoria-plzen",
    "Mladá Boleslav": "https://www.fotmob.com/teams/10180/squad/mlada-boleslav",
    "Karviná": "https://www.fotmob.com/teams/143833/squad/karvina",
    "Slovácko": "https://www.fotmob.com/teams/2021/squad/slovacko",
    "Slavia Praha": "https://www.fotmob.com/teams/7787/squad/slavia-prague",
    "Dukla Praha": "https://www.fotmob.com/teams/88657/squad/dukla-praha",
    "Baník Ostrava": "https://www.fotmob.com/teams/6362/squad/banik-ostrava",
    "Pardubice": "https://www.fotmob.com/teams/2406/squad/pardubice",
    "Táborsko": "https://www.fotmob.com/teams/157007/squad/fc-silon-taborsko",
    "Prostějov": "https://www.fotmob.com/teams/358094/squad/sk-prostejov",
    "Viktoria Žižkov": "https://www.fotmob.com/teams/6096/squad/zizkov",
    "Baník Ostrava II": "https://www.fotmob.com/teams/1154238/squad/banik-ostrava-b",
    "Zbrojovka Brno": "https://www.fotmob.com/teams/1673/squad/fc-zbrojovka-brno",
    "Chrudim": "https://www.fotmob.com/teams/279088/squad/mfk-chrudim",
    "Ústí nad Labem": "https://www.fotmob.com/teams/5733/squad/usti-nad-labem",
    "Příbram": "https://www.fotmob.com/teams/1672/squad/pribram",
    "Hanácká": "https://www.fotmob.com/teams/2404/squad/hanacka-slavia-kromeriz",
    "Vlašim": "https://www.fotmob.com/teams/175807/squad/fc-vlasim",
    "Sparta Praha II": "https://www.fotmob.com/teams/132215/squad/sparta-prague-b",
    "Opava": "https://www.fotmob.com/teams/1713/squad/opava",
    "Artis Brno": "https://www.fotmob.com/teams/106189/squad/artis-brno",
    "České Budějovice": "https://www.fotmob.com/teams/7840/squad/sk-dynamo-ceske-budejovice",
    "Slavia Praha II": "https://www.fotmob.com/teams/7787/squad/slavia-prague",
    "Vysočina Jihlava": "https://www.fotmob.com/teams/1949/squad/vysocina-jihlava",

    # --- DENMARK ---
    "OB": "https://www.fotmob.com/teams/8414/squad/ob",
    "København": "https://www.fotmob.com/teams/8391/squad/fc-kobenhavn",
    "Randers": "https://www.fotmob.com/teams/8410/squad/randers-fc",
    "Sønderjyske": "https://www.fotmob.com/teams/8487/squad/sonderjyske",
    "Viborg": "https://www.fotmob.com/teams/9939/squad/viborg",
    "Vejle": "https://www.fotmob.com/teams/8231/squad/vejle-boldklub",
    "Fredericia": "https://www.fotmob.com/teams/8454/squad/fredericia",
    "Brøndby": "https://www.fotmob.com/teams/8595/squad/brondby-if",
    "Silkeborg": "https://www.fotmob.com/teams/8415/squad/silkeborg",
    "Nordsjælland": "https://www.fotmob.com/teams/10202/squad/nordsjaelland",
    "Midtjylland": "https://www.fotmob.com/teams/8113/squad/fc-midtjylland",
    "AGF": "https://www.fotmob.com/teams/8071/squad/agf",
    "Horsens": "https://www.fotmob.com/teams/9814/squad/ac-horsens",
    "Lyngby": "https://www.fotmob.com/teams/9907/squad/lyngby",
    "AaB": "https://www.fotmob.com/teams/8470/squad/aab",
    "Hillerød": "https://www.fotmob.com/teams/9940/squad/hillerod",
    "Hobro": "https://www.fotmob.com/teams/9950/squad/hobro",
    "Middelfart": "https://www.fotmob.com/teams/9969/squad/middelfart",
    "B.93": "https://www.fotmob.com/teams/8453/squad/b-93",
    "Esbjerg": "https://www.fotmob.com/teams/8285/squad/esbjerg-fb",
    "Aarhus Fremad": "https://www.fotmob.com/teams/8109/squad/aarhus-fremad",
    "Hvidovre": "https://www.fotmob.com/teams/10240/squad/hvidovre",
    "Kolding IF": "https://www.fotmob.com/teams/6308/squad/kolding-if",
    "HB Køge": "https://www.fotmob.com/teams/8289/squad/hb-koge",

    # --- ECUADOR ---
    "Libertad": "",
    "Deportivo Cuenca": "",
    "Orense": "",
    "Emelec": "",
    "Macará": "",
    "Aucas": "",
    "Delfin": "",
    "LDU Quito": "",
    "Barcelona": "",
    "Independiente del Valle": "",
    "Técnico Universitario": "",
    "Manta": "",
    "Vinotinto de Ecuador": "",
    "El Nacional": "",
    "Mushuc Runa": "",

    # --- ESTONIA ---
    "Pärnu JK Vaprus": "",
    "Nõmme Kalju": "",
    "Kuressaare": "",
    "Flora": "",
    "Harju JK": "",
    "Tartu Tammeka": "",
    "Trans": "",
    "Levadia": "",
    "Paide": "",
    "Tallinna Kalev": "",

    # --- FINLAND ---
    "Inter Turku": "",
    "Ilves": "",
    "SJK": "",
    "HJK": "",
    "KTP": "",
    "Gnistan": "",
    "VPS": "",
    "KuPS": "",
    "Jaro": "",
    "Mariehamn": "",
    "Oulu": "",
    "Haka": "",

    # --- FRANCE ---
    "Nantes": "",
    "Toulouse": "",
    "Lens": "",
    "Le Havre": "",
    "Rennes": "",
    "Angers SCO": "",
    "Metz": "",
    "Lorient": "",
    "Nice": "",
    "Paris": "",
    "Strasbourg": "",
    "Brest": "",
    "Olympique Lyonnais": "",
    "Lille": "",
    "PSG": "",
    "Monaco": "",
    "Auxerre": "",
    "Olympique Marseille": "",
    "Guingamp": "",
    "Amiens SC": "",
    "Reims": "",
    "Saint-Étienne": "",
    "Le Mans": "",
    "Troyes": "",
    "Rodez": "",
    "Annecy": "",
    "Red Star": "",
    "Clermont": "",
    "Laval": "",
    "Grenoble": "",
    "Dunkerque": "",
    "Montpellier": "",
    "Boulogne": "",
    "Bastia": "",
    "Nancy": "",
    "Pau": "",
    "Villefranche": "",
    "Bourg-en-Bresse": "",
    "Le Puy F.43 Auvergne": "",
    "Aubagne": "",
    "Châteauroux": "",
    "Rouen": "",
    "Caen": "",
    "Concarneau": "",
    "Dijon": "",
    "Stade Briochin": "",
    "Fleury 91 FC": "",
    "Orléans": "",
    "Versailles": "",
    "Valenciennes": "",
    "Sochaux": "",
    "Quevilly Rouen": "",
    "Paris 13 Atletico": "",

    # --- GEORGIA ---
    "Torpedo Kutaisi": "",
    "Gagra": "",
    "Iberia 1999": "",
    "Dila": "",
    "Telavi": "",
    "Samgurali": "",
    "Dinamo Batumi": "",
    "Gareji": "",
    "Dinamo Tbilisi": "",
    "Kolkheti Poti": "",


   
}

# Normalized lookup
_FM = {_norm(k): v.strip() for k, v in FOTMOB_TEAM_URLS.items() if str(v).strip()}

def get_fotmob_url(team: str) -> str:
    return _FM.get(_norm(team), "")

